import {getOrder,bindings,saveOrder} from '@/lib/order-store';
import {tokenHash} from '@/lib/order-access';
import {approvalCurrent} from '@/lib/production';
import {PRIVATE_HEADERS} from '@/lib/admin-auth';
async function authorized(request:Request,id:string){const token=new URL(request.url).searchParams.get('token')||'';if(!/^[a-f0-9]{64}$/.test(token))return null;const o=await getOrder(id);if(o?.cancelledAt||o?.archivedAt||!o?.approval||o.approval.expiresAt<Date.now()||await tokenHash(token)!==o.approval.hash)return null;return o}
const unavailable=()=>Response.json({error:'הקישור אינו זמין או שפג תוקפו. בקשו מהסטודיו קישור מעודכן.'},{status:404,headers:PRIVATE_HEADERS});
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{const o=await authorized(request,(await params).id);if(!o)return unavailable();const a=o.approval!;if(!approvalCurrent(o)||a.state==='stale')return Response.json({error:'פרטי ההזמנה או העיצוב השתנו. בקשו קישור חדש.'},{status:409,headers:PRIVATE_HEADERS});const image=new URL(request.url).searchParams.get('image');if(image!==null){const i=Number(image);if(!Number.isInteger(i)||i<0||i>=a.images.length)return unavailable();const f=await bindings().BUCKET.get(a.images[i].key);if(!f)return unavailable();return new Response(f.body,{headers:{...PRIVATE_HEADERS,'Content-Type':f.httpMetadata?.contentType||'application/octet-stream'}})}return Response.json({id:o.id,approvalId:a.id,state:a.state,quantity:a.quantity,shirts:a.shirts,images:a.images.map(i=>({name:i.name})),createdAt:a.createdAt,respondedAt:a.respondedAt,comment:a.comment},{headers:PRIVATE_HEADERS})}catch{return unavailable()}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){if(request.headers.get('origin')!==new URL(request.url).origin)return new Response(null,{status:403,headers:PRIVATE_HEADERS});try{const o=await authorized(request,(await params).id);if(!o)return unavailable();const a=o.approval!;const raw=await request.text();if(raw.length>4000)return new Response(null,{status:413,headers:PRIVATE_HEADERS});let v;try{v=JSON.parse(raw)}catch{return new Response(null,{status:400,headers:PRIVATE_HEADERS})}if(!approvalCurrent(o)||a.state!=='pending'||v?.approvalId!==a.id)return Response.json({error:'העיצוב השתנה או שכבר התקבלה תשובה. רעננו את העמוד.'},{status:409,headers:PRIVATE_HEADERS});if(!['approved','changes'].includes(v.state)||typeof v.name!=='string'||!v.name.trim()||v.name.length>100||typeof v.comment!=='string'||v.comment.length>2000||v.state==='changes'&&!v.comment.trim())return Response.json({error:'יש למלא שם, ובבקשת תיקון גם פירוט השינוי.'},{status:400,headers:PRIVATE_HEADERS});const approval={...a,state:v.state as 'approved'|'changes',customerName:v.name.trim(),comment:v.comment.trim(),respondedAt:new Date().toISOString()};await saveOrder({...o,approval,status:v.state==='approved'?'approved':'designing'},o.version!,v.state==='approved'?'הלקוח אישר את גרסת העיצוב '+a.id:'הלקוח ביקש תיקון לגרסת העיצוב '+a.id,'לקוח באמצעות קישור פרטי');return Response.json({state:approval.state},{headers:PRIVATE_HEADERS})}catch{return Response.json({error:'לא ניתן לשמור כרגע. רעננו כדי לבדוק אם תשובתכם נשמרה.'},{status:409,headers:PRIVATE_HEADERS})}}

