'use client';
import {useEffect,useState} from 'react';
import {Order,STAGES} from '@/lib/orders';
import OrderActions from './order-actions';
export default function OrderBoard({params,revision,onOpen,onChange}:{params:string;revision:number;onOpen:(o:Order)=>void;onChange:()=>void}){
 const selected=new URLSearchParams(params).get('status');
 return <div className="order-board" aria-label="לוח הזמנות לפי שלבים">{STAGES.filter(([s])=>!selected||selected===s).map(([s,label],i)=><Column key={s+params} stage={s} label={label} color={i} params={params} revision={revision} onOpen={onOpen} onChange={onChange}/>)}</div>
}
function Column({stage,label,color,params,revision,onOpen,onChange}:{stage:string;label:string;color:number;params:string;revision:number;onOpen:(o:Order)=>void;onChange:()=>void}){
 const [page,setPage]=useState(0),[data,setData]=useState<{orders:Order[];total:number}>({orders:[],total:0}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();const p=new URLSearchParams(params);p.set('status',stage);p.set('page',String(page));fetch('/api/admin/orders?'+p,{signal:controller.signal}).then(async r=>{const v=await r.json() as {orders:Order[];total:number;error?:string};if(!r.ok)throw Error(v.error||'לא ניתן לטעון הזמנות');if(page>0&&!v.orders.length){setPage(0);return}setData(v)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[params,stage,page,revision]);
 return <section className="board-column" aria-busy={loading}><header className={'stage-'+color}><h3>{label}</h3><b>{data.total}</b></header>{error&&<p className="studio-error" role="alert">{error}<button onClick={onChange}>ניסיון נוסף</button></p>}{loading&&<p role="status">טוענים…</p>}{data.orders.map(o=><article className="board-card" key={o.id}><button className="board-open" onClick={()=>onOpen(o)}><small>#{o.id.slice(0,8).toUpperCase()}</small><h4>{o.name}</h4><span>{o.packageName} · {o.quantity} חולצות</span><strong>{o.price.toLocaleString('he-IL')} ₪</strong>{o.dueDate&&<small>מועד יעד: {o.dueDate}</small>}</button><OrderActions order={o} onChange={onChange}/></article>)}{!loading&&!data.orders.length&&!error&&<p className="board-empty">אין הזמנות בשלב הזה לפי הסינון.</p>}{data.total>40&&<div className="board-pages"><button disabled={!page||loading} onClick={()=>setPage(v=>v-1)}>הקודם</button><span>{page+1}/{Math.ceil(data.total/40)}</span><button disabled={(page+1)*40>=data.total||loading} onClick={()=>setPage(v=>v+1)}>הבא</button></div>}</section>
}
