'use client';
/* eslint-disable @next/next/no-img-element -- profile images are private admin API responses. */
import {useCallback,useEffect,useRef,useState} from 'react';
type Profile={email:string;name:string;role:string;avatarUrl:string|null;isOwner:boolean};
export default function ProfileEditor({targetEmail,compact=false}:{targetEmail?:string;compact?:boolean}){
 const [profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const input=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{try{const r=await fetch('/api/admin/profile'+(targetEmail?'?email='+encodeURIComponent(targetEmail):''));const v=await r.json() as {profile?:Profile;error?:string};if(!r.ok||!v.profile)throw Error(v.error||'לא ניתן לטעון את הפרופיל');setProfile(v.profile);setName(v.profile.name);setPreview(v.profile.avatarUrl||'');setError('')}catch(e){setError((e as Error).message)}},[targetEmail]);
 useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load]);
 async function save(e:React.FormEvent){e.preventDefault();if(!profile||busy)return;if(!name.trim()){setError('הזינו שם לתצוגה.');return}setBusy(true);setError('');setNotice('');const form=new FormData();form.set('name',name.trim());if(targetEmail)form.set('targetEmail',targetEmail);if(file)form.set('avatar',file);try{const r=await fetch('/api/admin/profile',{method:'POST',body:form});const v=await r.json() as {profile?:Profile;error?:string};if(!r.ok||!v.profile)throw Error(v.error||'לא ניתן לשמור את הפרופיל');setProfile(v.profile);setName(v.profile.name);setPreview(v.profile.avatarUrl||'');setFile(null);if(input.current)input.current.value='';setNotice('הפרופיל נשמר.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!profile)return error?<div className={compact?'profile-editor compact':'profile-editor'}><p className="studio-error" role="alert">{error}</p></div>:<div className={compact?'profile-editor compact':'profile-editor'}><p role="status">טוענים פרופיל…</p></div>;
 return <div className={'profile-editor'+(compact?' compact':'')}><div className="profile-editor-heading"><div className="profile-avatar">{preview?<img src={preview} alt=""/>:<span>{name.slice(0,1)||'?'}</span>}</div><div><b>{targetEmail?'פרופיל המשתמש':'הפרופיל שלי'}</b><small dir="ltr">{profile.email}</small><span>{profile.role==='owner'?'בעל האתר':profile.role==='manager'?'מנהל סטודיו':profile.role==='designer'?'עיצוב':'הדפסה'}</span></div></div><form onSubmit={save}><fieldset className="editor-fields" disabled={busy}><label>שם לתצוגה<input value={name} maxLength={100} onChange={e=>setName(e.target.value)} required/></label><label>תמונת פרופיל<input ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const next=e.target.files?.[0]||null;setFile(next);if(next)setPreview(URL.createObjectURL(next))}}/><small>JPG, PNG או WEBP · עד 2MB</small></label><button className="save-order">{busy?'שומרים…':'שמירת פרופיל'}</button></fieldset></form>{error&&<p role="alert" className="studio-error">{error}</p>}{notice&&<p role="status" className="settings-notice">{notice}</p>}</div>
}
