'use client';
import {useEffect,useState} from 'react';
import {Save,Plus,TicketPercent,Tag,Shirt,LoaderCircle,CheckCircle2,X} from 'lucide-react';
import {Pricing,Coupon,DEFAULT_PRICING} from '@/lib/pricing';
import {packs} from '@/lib/catalog';
const blank:Coupon={code:'',title:'',kind:'percent',value:10,minQuantity:0,minSubtotal:0,maxUses:0,starts:'',ends:'',enabled:true,package:-1,used:0,version:0};
export default function Settings({onDirty}:{onDirty:(dirty:boolean)=>void}){const [pricing,setPricing]=useState<Pricing>(DEFAULT_PRICING),[coupons,setCoupons]=useState<Coupon[]>([]),[edit,setEdit]=useState<Coupon|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[changed,setChanged]=useState(false);
 useEffect(()=>{onDirty(changed||!!edit)},[changed,edit,onDirty]);useEffect(()=>()=>onDirty(false),[onDirty]);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/settings');const v=await r.json() as {error?:string;pricing:Pricing;coupons:Coupon[]};if(!r.ok)throw Error(v.error);setPricing(v.pricing);setCoupons(v.coupons);setError('');setChanged(false)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function save(action:string,coupon?:Coupon){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,pricing,coupon})});const v=await r.json() as {error?:string;pricing:Pricing;coupons:Coupon[]};if(!r.ok)throw Error(v.error);if(action==='pricing'){setPricing(v.pricing);setChanged(false)}setCoupons(v.coupons);setEdit(null);setNotice(action==='pricing'?'המחירים עודכנו באתר. הזמנות קיימות שומרות על המחיר שנקבע להן.':'קוד המבצע נשמר ויעובד לפי התנאים שהגדרתם.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function field<K extends keyof Coupon>(k:K,v:Coupon[K]){setEdit(c=>c?{...c,[k]:v}:c)}
 return <section className="settings-view"><div className="settings-heading"><div><span className="studio-kicker">המחיר הנכון. לכל חגיגה.</span><h2>מחירים ומבצעים</h2></div><Tag size={32}/></div>{error&&<p className="studio-error" role="alert">{error} <button disabled={busy} onClick={()=>{if(!changed||confirm('לרענן ולוותר על שינויי המחיר שלא נשמרו?'))void load()}}>רענון</button></p>}{notice&&<p className="save-success settings-notice" role="status"><CheckCircle2 size={18}/>{notice}</p>}{loading?<p>טוענים הגדרות…</p>:<><section className="settings-card"><div className="settings-card-title"><Shirt/><div><h3>מחירון החולצות</h3><p>מחירי חבילה כוללים עיצוב, הדפסה ומשלוח. השינויים חלים על הזמנות חדשות.</p></div></div><fieldset disabled={busy} className="editor-fields"><div className="price-settings-grid">{packs.slice(0,4).map((p,i)=><label key={p.name}>{p.name} · {p.n} חולצות<input type="number" min={1} max={100000} value={pricing.basePrices[i]} onChange={e=>{setPricing(v=>({...v,basePrices:v.basePrices.map((x,n)=>n===i?Number(e.target.value):x)}));setChanged(true)}}/><small>{Math.round(pricing.basePrices[i]/p.n)} ₪ לחולצה בממוצע</small></label>)}</div><div className="extra-shirt-setting"><label>מחיר כל חולצה נוספת (₪)<input type="number" min={1} max={100000} value={pricing.extraShirtPrice} onChange={e=>{setPricing(v=>({...v,extraShirtPrice:Number(e.target.value)}));setChanged(true)}}/></label><p>התוספת מעבר לכמות הבסיס בחבילות המשפחה, הרווקות, הרווקים והצוות.</p></div><h4>חבילת ״הרעיון שלכם״</h4><div className="price-settings-grid">{[5,10,15,20].map(n=><label key={n}>{n} חולצות (₪)<input type="number" min={1} max={100000} value={pricing.customPrices[n]} onChange={e=>{setPricing(v=>({...v,customPrices:{...v.customPrices,[n]:Number(e.target.value)}}));setChanged(true)}}/></label>)}</div></fieldset><div className="settings-save"><span>{changed?'יש שינויי מחיר שלא נשמרו':'המחירון מעודכן'}</span><button className="save-order" disabled={busy||!changed} onClick={()=>void save('pricing')}><Save size={18}/> פרסום המחירים באתר</button></div></section>
 <section className="settings-card"><div className="settings-card-title"><TicketPercent/><div><h3>קודי מבצע</h3><p>הנחה באחוזים או בשקלים, עם תוקף, הגבלת שימוש ותנאי חבילה.</p></div><button className="studio-text" disabled={busy} onClick={()=>setEdit({...blank})}><Plus size={19}/> קוד חדש</button></div><div className="coupon-list">{coupons.map(c=><button key={c.code} className="coupon-card" onClick={()=>setEdit({...c})}><div><b dir="ltr">{c.code}</b><span className={c.enabled?'coupon-on':'coupon-off'}>{c.enabled?'מופעל':'מושבת'}</span></div><strong>{c.value}{c.kind==='percent'?'%':' ₪'} הנחה</strong><p>{c.title||'מבצע לחולצות בעיצוב אישי'}</p><small>{c.used} שימושים{c.maxUses?' מתוך '+c.maxUses:''} · {c.ends?'עד '+c.ends:'ללא תאריך סיום'}</small></button>)}</div>{!coupons.length&&<p className="studio-note">עדיין אין קודי מבצע. צרו קוד לקמפיין הבא שלכם.</p>}<p className="studio-note">שימוש נספר בעת שמירת בקשת הזמנה, גם לפני תשלום. קוד אחד להזמנה. השבתת קוד שומרת את היסטוריית השימושים. תאריכים לפי שעון ישראל.</p>
 {edit&&<form className="coupon-editor" onSubmit={e=>{e.preventDefault();void save('coupon',edit)}}><div className="settings-card-title"><h3>{edit.version?'עריכת קוד '+edit.code:'מבצע חדש'}</h3><button type="button" className="studio-icon" aria-label="סגירת עריכת קוד" onClick={()=>setEdit(null)}><X size={18}/></button></div><fieldset disabled={busy} className="editor-fields"><div className="editor-two"><label>קוד המבצע<input required value={edit.code} disabled={edit.version>0} dir="ltr" pattern="[A-Za-z0-9_-]{3,30}" maxLength={30} placeholder="PARTY10" onChange={e=>field('code',e.target.value.toUpperCase())}/></label><label>שם המבצע<input value={edit.title} maxLength={100} onChange={e=>field('title',e.target.value)} placeholder="חגיגת פתיחת האתר"/></label></div><div className="editor-two"><label>סוג הנחה<select value={edit.kind} onChange={e=>field('kind',e.target.value as 'percent'|'fixed')}><option value="percent">אחוזים</option><option value="fixed">סכום בשקלים</option></select></label><label>גובה ההנחה<input type="number" min={1} max={edit.kind==='percent'?100:100000} required value={edit.value} onChange={e=>field('value',Number(e.target.value))}/></label></div><div className="editor-two"><label>בתוקף מתאריך<input type="date" value={edit.starts} onChange={e=>field('starts',e.target.value)}/></label><label>בתוקף עד תאריך<input type="date" value={edit.ends} onChange={e=>field('ends',e.target.value)}/></label></div><div className="editor-two"><label>מינימום חולצות<input type="number" min={0} value={edit.minQuantity} onChange={e=>field('minQuantity',Number(e.target.value))}/></label><label>סכום מינימלי לפני הנחה<input type="number" min={0} value={edit.minSubtotal} onChange={e=>field('minSubtotal',Number(e.target.value))}/></label></div><div className="editor-two"><label>כמות שימושים מרבית (0 = ללא הגבלה)<input type="number" min={0} value={edit.maxUses} onChange={e=>field('maxUses',Number(e.target.value))}/></label><label>חבילה משתתפת<select value={edit.package} onChange={e=>field('package',Number(e.target.value))}><option value={-1}>כל החבילות</option>{packs.map((p,i)=><option key={i} value={i}>{p.name}</option>)}</select></label></div><label>מצב הקוד<select value={edit.enabled?'on':'off'} onChange={e=>field('enabled',e.target.value==='on')}><option value="on">מופעל בהתאם לתוקף ולתנאים</option><option value="off">מושבת</option></select></label></fieldset><button className="save-order" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Save size={18}/>} שמירת המבצע</button></form>}</section></>}</section>
}
