'use client';

import {useEffect,useState} from 'react';
import {Save,Plus,TicketPercent,Tag,Shirt,LoaderCircle,CheckCircle2,X} from 'lucide-react';
import {Coupon,DEFAULT_PRICING,PriceTier,Pricing,priceFor,unitPriceFor,validPricing} from '@/lib/pricing';
import {packs} from '@/lib/catalog';

const blank:Coupon={code:'',title:'',kind:'percent',value:10,minQuantity:0,minSubtotal:0,maxUses:0,starts:'',ends:'',enabled:true,package:-1,used:0,version:0};

function TierEditor({pricing,savedPricing,onChange}:{pricing:Pricing;savedPricing:Pricing;onChange:(tiers:PriceTier[])=>void}){
 return <>
  <div className="tier-intro"><div><b>מחיר החולצה נקבע לפי הכמות</b><p>המחיר כולל עיצוב משותף, הדפסה ומשלוח עד הבית. כל מדרגה חלה מהכמות שלה ועד למדרגה הבאה.</p></div><span>₪ לחולצה</span></div>
  <div className="tier-table" role="table" aria-label="מדרגות מחיר לפי כמות">
   <div className="tier-row tier-head" role="row"><span>מכמות</span><span>מחיר לחולצה</span><span>מחיר החבילה</span></div>
   {pricing.tiers.map((tier,i)=>{const next=pricing.tiers[i+1]?.quantity;const quantity=tier.quantity;const total=Number.isFinite(quantity)&&quantity>0?Math.round(unitPriceFor(pricing,quantity)*quantity*100)/100:0;return <div className="tier-row" role="row" key={i}>
    <label><span className="sr-only">מכמות</span><input aria-label={`מכמות מדרגה ${i+1}`} type="number" min={1} max={100} step={1} value={tier.quantity||''} onChange={e=>onChange(pricing.tiers.map((v,n)=>n===i?{...v,quantity:Number(e.target.value)}:v))}/><small>{next?`עד ${next-1} חולצות`: 'ומעלה'}</small></label>
    <label><span className="sr-only">מחיר לחולצה</span><input aria-label={`מחיר לחולצה מדרגה ${i+1}`} type="number" min={0.01} max={1000} step={0.01} inputMode="decimal" value={tier.price||''} onChange={e=>onChange(pricing.tiers.map((v,n)=>n===i?{...v,price:Number(e.target.value)}:v))}/><small>כולל הכול</small></label>
    <strong>{total.toLocaleString('he-IL')} ₪</strong>
   </div>})}
  </div>
  {!validPricing(pricing)&&<p role="alert" className="studio-error">המדרגות חייבות להיות בסדר עולה, והמחירים בין 0.01 ל־1,000 ₪ עם עד שתי ספרות אחרי הנקודה.</p>}
  <div className="tier-saved-note">{savedPricing.tiers.length?<>המחירים שפורסמו: {savedPricing.tiers.map(t=>`${t.quantity}+ · ${t.price.toLocaleString('he-IL')} ₪`).join('  |  ')}</>:null}</div>
  <h4>{'מחירי החבילות לפי ההגדרות הנוכחיות'}</h4>
  <div className="unit-pack-preview" aria-live="polite">{packs.map((p,i)=><article key={p.name}><span>{p.name}</span><small>{p.n} חולצות × {unitPriceFor(pricing,p.n).toLocaleString('he-IL')} ₪</small><strong>{priceFor(pricing,i,p.n).toLocaleString('he-IL')} ₪</strong></article>)}</div>
  <p className="studio-note">המחיר באתר מתעדכן לפי הכמות בפועל. הזמנות שכבר התקבלו שומרות את המחיר שנקבע בזמן השליחה.</p>
 </>;
}

export default function Settings({onDirty}:{onDirty:(dirty:boolean)=>void}){
 const [pricing,setPricing]=useState<Pricing>(DEFAULT_PRICING),[savedPricing,setSavedPricing]=useState<Pricing>(DEFAULT_PRICING),[coupons,setCoupons]=useState<Coupon[]>([]),[edit,setEdit]=useState<Coupon|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[changed,setChanged]=useState(false);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(changed||edit){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[changed,edit]);
 useEffect(()=>{onDirty(changed||!!edit)},[changed,edit,onDirty]);
 useEffect(()=>()=>onDirty(false),[onDirty]);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/settings');const v=await r.json() as {error?:string;pricing:Pricing;coupons:Coupon[]};if(!r.ok)throw Error(v.error);setPricing(v.pricing);setSavedPricing(v.pricing);setCoupons(v.coupons);setError('');setChanged(false)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function save(action:string,coupon?:Coupon){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,pricing,coupon})});const v=await r.json() as {error?:string;pricing:Pricing;coupons:Coupon[]};if(!r.ok)throw Error(v.error);if(action==='pricing'){setPricing(v.pricing);setSavedPricing(v.pricing);setChanged(false);setNotice('מדרגות המחיר עודכנו באתר. הזמנות קיימות שומרות על המחיר שנקבע להן.')}else{setEdit(null);setNotice('קוד המבצע נשמר ויעובד לפי התנאים שהגדרתם.')}setCoupons(v.coupons)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function updateTiers(tiers:PriceTier[]){setPricing(v=>({...v,tiers}));setChanged(true);setNotice('')}
 function field<K extends keyof Coupon>(k:K,v:Coupon[K]){setEdit(c=>c?{...c,[k]:v}:c)}
 return <section className="settings-view"><div className="settings-heading"><div><span className="studio-kicker">המחיר הנכון. לכל חגיגה.</span><h2>מחירים ומבצעים</h2></div><Tag size={32}/></div>{error&&<p className="studio-error" role="alert">{error} <button disabled={busy} onClick={()=>{if(!(changed||edit)||confirm('לרענן ולוותר על השינויים שלא נשמרו?'))void load()}}>רענון</button></p>}{notice&&<p className="save-success settings-notice" role="status"><CheckCircle2 size={18}/>{notice}</p>}{loading?<p>טוענים הגדרות…</p>:<>
  <section className="settings-card"><div className="settings-card-title"><Shirt/><div><h3>מדרגות מחיר לחולצה</h3><p>אותו מחירון לכל החבילות. המחיר ליחידה כולל עיצוב, הדפסה ומשלוח עד הבית.</p></div></div><fieldset disabled={busy} className="editor-fields"><TierEditor pricing={pricing} savedPricing={savedPricing} onChange={updateTiers}/></fieldset><div className="settings-save"><span>{changed?'יש שינויי מחיר שלא נשמרו':'המחירון מעודכן'}</span><button className="save-order" disabled={busy||!changed||!validPricing(pricing)} onClick={()=>void save('pricing')}><Save size={18}/> פרסום המחירים באתר</button></div></section>
  <section className="settings-card"><div className="settings-card-title"><TicketPercent/><div><h3>קודי מבצע</h3><p>הנחה באחוזים או בשקלים, עם תוקף, הגבלת שימוש ותנאי חבילה.</p></div><button className="studio-text" disabled={busy} onClick={()=>setEdit({...blank})}><Plus size={19}/> קוד חדש</button></div><div className="coupon-list">{coupons.map(c=><button key={c.code} className="coupon-card" onClick={()=>setEdit({...c})}><div><b dir="ltr">{c.code}</b><span className={c.enabled?'coupon-on':'coupon-off'}>{c.enabled?'מופעל':'מושבת'}</span></div><strong>{c.value}{c.kind==='percent'?'%':' ₪'} הנחה</strong><p>{c.title||'מבצע לחולצות בעיצוב אישי'}</p><small>{c.used} שימושים{c.maxUses?' מתוך '+c.maxUses:''} · {c.ends?'עד '+c.ends:'ללא תאריך סיום'}</small></button>)}</div>{!coupons.length&&<p className="studio-note">עדיין אין קודי מבצע. צרו קוד לקמפיין הבא שלכם.</p>}<p className="studio-note">שימוש נספר בעת שמירת בקשת הזמנה, גם לפני תשלום. קוד אחד להזמנה. השבתת קוד שומרת את היסטוריית השימושים. תאריכים לפי שעון ישראל.</p>
  {edit&&<form className="coupon-editor" onSubmit={e=>{e.preventDefault();void save('coupon',edit)}}><div className="settings-card-title"><h3>{edit.version?'עריכת קוד '+edit.code:'מבצע חדש'}</h3><button type="button" className="studio-icon" aria-label="סגירת עריכת קוד" onClick={()=>setEdit(null)}><X size={18}/></button></div><fieldset disabled={busy} className="editor-fields"><div className="editor-two"><label>קוד המבצע<input required value={edit.code} disabled={edit.version>0} dir="ltr" pattern="[A-Za-z0-9_-]{3,30}" maxLength={30} placeholder="PARTY10" onChange={e=>field('code',e.target.value.toUpperCase())}/></label><label>שם המבצע<input value={edit.title} maxLength={100} onChange={e=>field('title',e.target.value)} placeholder="חגיגת פתיחת האתר"/></label></div><div className="editor-two"><label>סוג הנחה<select value={edit.kind} onChange={e=>field('kind',e.target.value as 'percent'|'fixed')}><option value="percent">אחוזים</option><option value="fixed">סכום בשקלים</option></select></label><label>גובה ההנחה<input type="number" min={1} max={edit.kind==='percent'?100:100000} required value={edit.value} onChange={e=>field('value',Number(e.target.value))}/></label></div><div className="editor-two"><label>בתוקף מתאריך<input type="date" value={edit.starts} onChange={e=>field('starts',e.target.value)}/></label><label>בתוקף עד תאריך<input type="date" value={edit.ends} onChange={e=>field('ends',e.target.value)}/></label></div><div className="editor-two"><label>מינימום חולצות<input type="number" min={0} value={edit.minQuantity} onChange={e=>field('minQuantity',Number(e.target.value))}/></label><label>סכום מינימלי לפני הנחה<input type="number" min={0} value={edit.minSubtotal} onChange={e=>field('minSubtotal',Number(e.target.value))}/></label></div><div className="editor-two"><label>כמות שימושים מרבית (0 = ללא הגבלה)<input type="number" min={0} value={edit.maxUses} onChange={e=>field('maxUses',Number(e.target.value))}/></label><label>חבילה משתתפת<select value={edit.package} onChange={e=>field('package',Number(e.target.value))}><option value={-1}>כל החבילות</option>{packs.map((p,i)=><option key={i} value={i}>{p.name}</option>)}</select></label></div><label>מצב הקוד<select value={edit.enabled?'on':'off'} onChange={e=>field('enabled',e.target.value==='on')}><option value="on">מופעל בהתאם לתוקף ולתנאים</option><option value="off">מושבת</option></select></label></fieldset><button className="save-order" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Save size={18}/>} שמירת המבצע</button></form>}</section>
 </>}</section>;
}
