'use client';
import Settings from './settings';
import Analytics from './analytics';
import {israelDay} from '@/lib/admin-query';
import {DEFAULT_PRICING,Pricing,priceFor} from '@/lib/pricing';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpLeft,Check,ChevronLeft,ChevronRight,Download,ImagePlus,LoaderCircle,Mail,MessageCircle,Package,RefreshCw,Save,Search,Shirt,Trash2,X,Clock,SlidersHorizontal,CheckCircle2,ExternalLink} from 'lucide-react';
import {Order,STAGES,stageLabel,whatsappLink} from '@/lib/orders';
import {packs,calculatePrice,COLORS,COLOR_LABELS,SIZES} from '@/lib/catalog';
import {imageUploadError} from '@/lib/upload-limits';
const date=(s?:string)=>s?new Date(s).toLocaleDateString('he-IL'):'';
const money=(n:number)=>n.toLocaleString('he-IL')+' ₪';
const roles:Record<string,string>={reference:'תמונת רפרנס',design:'עיצוב לאישור',print:'עיצוב להדפסה'};
type Listing={orders:Order[];total:number;counts:{status:string;n:number}[];mailReady:boolean;pendingMail:number;attention?:{overdue:number;today:number};today?:string};
async function api<T>(url:string,init?:RequestInit){const response=await fetch(url,init);const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||'לא ניתן להשלים את הפעולה.');return data as T}
export default function Admin(){
 const [view,setView]=useState('orders'),[settingsDirty,setSettingsDirty]=useState(false),[refresh,setRefresh]=useState(0);
 function switchView(next:string){if(view==='settings'&&settingsDirty&&!confirm('יש הגדרות שלא נשמרו. לעבור בלי לשמור?'))return;setView(next)}
 const [data,setData]=useState<Listing>({orders:[],total:0,counts:[],mailReady:false,pendingMail:0}),[q,setQ]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Order|null>(null),[syncing,setSyncing]=useState(false),[notice,setNotice]=useState('');const seq=useRef(0);
 useEffect(()=>{const t=setTimeout(()=>{setQuery(q);setPage(0)},300);return()=>clearTimeout(t)},[q]);
 const [focus,setFocus]=useState(''),[sort,setSort]=useState('newest'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[exporting,setExporting]=useState(false);
 const params=new URLSearchParams({q:query,status,focus,sort,from,to,page:String(page)}).toString();
 const load=useCallback(async()=>{const n=++seq.current;setLoading(true);setError('');try{const result=await api<Listing>(`/api/admin/orders?${params}`);if(n===seq.current)setData(result)}catch(e){if(n===seq.current)setError((e as Error).message)}finally{if(n===seq.current)setLoading(false)}},[params]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const id=new URL(location.href).searchParams.get('order');if(id)api<Order>('/api/admin/orders/'+encodeURIComponent(id)).then(setSelected).catch(e=>setError(e.message))},[]);
 async function sync(){setSyncing(true);setNotice('');try{let cursor:string|null=null,total=0;do{const result:{cursor:string|null;imported:number}=await api<{cursor:string|null;imported:number}>('/api/admin/orders'+(cursor?'?cursor='+encodeURIComponent(cursor):''),{method:'POST'});cursor=result.cursor;total+=result.imported}while(cursor);setNotice(total?`${total} הזמנות קודמות נוספו למערכת`:'כל ההזמנות הקודמות מסונכרנות');await load()}catch(e){setError((e as Error).message)}finally{setSyncing(false)}}
 useEffect(()=>{void sync()},[]);
 async function exportOrders(){setExporting(true);setError('');try{const response=await fetch('/api/admin/orders/export?'+params);if(!response.ok){const result=await response.json() as {error?:string};throw Error(result.error||'הייצוא נכשל.')}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='partyprint-orders-'+israelDay()+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}finally{setExporting(false)}}
 function chooseFocus(value:string){setFocus(value);setPage(0)}
 const all=data.counts.reduce((n,c)=>n+c.n,0),done=data.counts.find(c=>c.status==='shipped')?.n||0;
 function open(o:Order){setSelected(o);history.replaceState(null,'','/admin?order='+o.id)}
 function close(){setSelected(null);history.replaceState(null,'','/admin');void load()}
 return <main className="studio" dir="rtl"><aside className="studio-rail"><a href="/" className="studio-brand" dir="ltr">PARTY<span>PRINT</span><i>✳</i></a><span className="studio-tag">STUDIO / CONTROL ROOM</span><a className="rail-active" href="/admin"><Package size={19}/> הזמנות</a><a href="/" target="_blank" rel="noreferrer"><ExternalLink size={18}/> צפייה באתר</a><div className="rail-bottom"><b>דניאל אציל</b><span>ניהול הסטודיו</span><a href="/signout-with-chatgpt?return_to=/">יציאה מהחשבון</a></div></aside><div className="studio-work"><header className="studio-top"><div><span className="studio-kicker">מהרעיון. עד הדלת.</span><h1>ההזמנות של הסטודיו<span>✳</span></h1><p>כל האנשים, החולצות והשלבים. במקום אחד.</p></div><button className="studio-icon" onClick={()=>{if(view==='orders')void load();else if(!settingsDirty||confirm('לרענן ולוותר על השינויים שלא נשמרו?'))setRefresh(v=>v+1)}} aria-label="רענון נתונים"><RefreshCw size={20} className={loading?'spin':''}/></button></header><nav className="studio-main-tabs" aria-label="ניהול הסטודיו">{[["orders","הזמנות"],["settings","מחירים ומבצעים"],["analytics","סטטיסטיקות ואנליטיקה"]].map(([k,l])=><button key={k} className={view===k?"active":""} onClick={()=>switchView(k)}>{l}</button>)}</nav>{view==='orders'?<>
 <div className="studio-stats"><div><span>בטיפול</span><strong>{all-done}</strong><small>רעיונות בדרך להפוך לחולצות</small></div><div><span>ממתינות לאישור עיצוב</span><strong>{data.counts.find(c=>c.status==='review')?.n||0}</strong><small>זמן לבדוק עם הלקוח</small></div><div><span>מוכנות למשלוח</span><strong>{data.counts.find(c=>c.status==='printed')?.n||0}</strong><small>השלב האחרון לפני הדלת</small></div><div><span>נשלחו ללקוחות</span><strong>{done}</strong><small>מתוך {all} הזמנות</small></div></div>
 {!loading&&!data.mailReady&&<div className="studio-banner"><Mail size={22}/><div><b>ההזמנות נשמרות. שירות המייל עדיין לא מחובר.</b><p>כדי לקבל התראות ל־atzilul@gmail.com נדרשים שירות דיוור וכתובת שולח מאומתת. כל ההזמנות זמינות כאן גם ללא מייל.</p></div></div>}
 <div className="attention-bar" aria-label="משימות לטיפול"><button aria-pressed={focus==='overdue'} onClick={()=>chooseFocus(focus==='overdue'?'':'overdue')}><Clock size={18}/><b>{data.attention?.overdue||0}</b> עבר מועד היעד</button><button aria-pressed={focus==='today'} onClick={()=>chooseFocus(focus==='today'?'':'today')}><Package size={18}/><b>{data.attention?.today||0}</b> להיום</button><button aria-pressed={focus==='no_mail'} onClick={()=>chooseFocus(focus==='no_mail'?'':'no_mail')}><Mail size={18}/><b>{data.pendingMail}</b> ללא התראת מייל</button></div>
 <nav className="stage-filters" aria-label="סינון לפי שלב"><button className={!status?'active':''} onClick={()=>{setStatus('');setPage(0)}}>הכול <b>{all}</b></button>{STAGES.map(([s,label],i)=><button key={s} className={status===s?'active':''} onClick={()=>{setStatus(s);setPage(0)}}><span className={'stage-dot stage-'+i}/>{label}<b>{data.counts.find(c=>c.status===s)?.n||0}</b></button>)}</nav>
 <div className="studio-toolbar"><label className="studio-search"><Search size={20}/><input aria-label="חיפוש הזמנות" value={q} onChange={e=>setQ(e.target.value)} placeholder="שם, טלפון, מייל או מספר הזמנה"/>{q&&<button onClick={()=>setQ('')} aria-label="ניקוי חיפוש"><X size={17}/></button>}</label><span>{data.total} הזמנות</span><button className="studio-text" disabled={syncing} onClick={()=>void sync()}><RefreshCw size={16} className={syncing?'spin':''}/> סנכרון הזמנות קודמות</button></div>
 <details className="order-filter-panel"><summary><SlidersHorizontal size={18}/> מיון, סינון וייצוא {Boolean(focus||from||to)&&<b>סינון פעיל</b>}</summary><div className="order-filter-fields"><label>תצוגה<select value={focus} onChange={e=>chooseFocus(e.target.value)}><option value="">כל הפניות</option><option value="open">הזמנות בטיפול</option><option value="overdue">עבר מועד היעד</option><option value="today">מועד יעד היום</option><option value="no_mail">ללא התראת מייל</option><option value="lead">התייעצויות</option></select></label><label>מיון<select value={sort} onChange={e=>{setSort(e.target.value);setPage(0)}}><option value="newest">החדשות קודם</option><option value="oldest">הוותיקות קודם</option><option value="due">מועד היעד הקרוב</option><option value="updated">עודכנו לאחרונה</option><option value="value">הסכום הגבוה קודם</option></select></label><label>מועד יעד מתאריך<input type="date" value={from} max={to||undefined} onChange={e=>{setFrom(e.target.value);setPage(0)}}/></label><label>מועד יעד עד תאריך<input type="date" value={to} min={from||undefined} onChange={e=>{setTo(e.target.value);setPage(0)}}/></label></div><div className="filter-actions"><button className="studio-text" onClick={()=>{setQ('');setStatus('');setFocus('');setFrom('');setTo('');setSort('newest');setPage(0)}}>ניקוי כל הסינונים</button><button className="studio-text" disabled={exporting||loading} onClick={()=>void exportOrders()}><Download size={18}/>{exporting?'מכינים קובץ…':'ייצוא התוצאות לאקסל (CSV)'}</button></div><p className="studio-note">המועדים לפי שעון ישראל. הייצוא כולל את כל תוצאות הסינון, עד 5,000 הזמנות, ולא רק את העמוד הנוכחי.</p></details>
 {notice&&<p className="studio-note" role="status">{notice}</p>}{error&&<div className="studio-error" role="alert">{error}<button onClick={()=>void load()}>ניסיון נוסף</button></div>}
 <div className="order-grid" aria-busy={loading}>{data.orders.map(o=>{const overdue=o.dueDate&&o.dueDate<(data.today||israelDay())&&o.status!=='shipped';return <button className="order-card" key={o.id} onClick={()=>open(o)}><div className="order-card-top"><span className={'status-badge stage-'+Math.max(0,STAGES.findIndex(s=>s[0]===o.status))}>{stageLabel(o.status)}</span><small dir="ltr">#{o.id.slice(0,8).toUpperCase()}</small></div><h2>{o.name}</h2><p>{o.packageName} {o.mode==='lead'&&<b>· התייעצות</b>}</p><div className="order-card-facts"><span><Shirt size={17}/>{o.quantity} חולצות</span><strong>{money(o.price)}</strong></div><div className="order-thumbnails">{o.images.slice(0,3).map(img=><img key={img.key} src={`/api/admin/orders/${o.id}/image?key=${encodeURIComponent(img.key)}`} alt={img.name} loading="lazy"/>)}{!o.images.length&&<span><ImagePlus size={18}/> טרם צורפו תמונות</span>}{o.images.length>3&&<b>+{o.images.length-3}</b>}</div><div className="order-card-bottom"><span>{overdue?'מועד היעד עבר':o.dueDate?'יעד: '+date(o.dueDate):date(o.createdAt)}</span><span className={o.emailStatus==='accepted'?'mail-ok':'mail-pending'}><Mail size={14}/>{o.emailStatus==='accepted'?'התראה הועברה':'טרם נשלח מייל'}</span><ArrowUpLeft size={19}/></div></button>})}</div>
 {!loading&&!data.orders.length&&!error&&<div className="studio-empty"><Package size={44}/><h2>{query||status||focus||from||to?'לא נמצאו הזמנות מתאימות':'החגיגה הבאה מתחילה כאן'}</h2><p>{query||status||focus||from||to?'נסו לשנות את החיפוש או הסינון.':'כל פנייה חדשה מהאתר תופיע כאן אוטומטית עם הפרטים והתמונות.'}</p></div>}
 {loading&&!data.orders.length&&<div className="studio-empty"><LoaderCircle className="spin"/> טוענים הזמנות…</div>}
 <div className="studio-pagination"><button disabled={page===0||loading} onClick={()=>setPage(v=>v-1)}><ChevronRight size={18}/> הקודם</button><span>עמוד {page+1} מתוך {Math.max(1,Math.ceil(data.total/40))}</span><button disabled={(page+1)*40>=data.total||loading} onClick={()=>setPage(v=>v+1)}>הבא <ChevronLeft size={18}/></button></div></>:view==='settings'?<Settings key={refresh} onDirty={setSettingsDirty}/>:<Analytics key={refresh}/>}</div>
 {selected&&<Editor key={selected.id} initial={selected} onClose={close} onSave={o=>{setSelected(o);void load()}}/>}</main>
}
function Editor({initial,onClose,onSave}:{initial:Order;onClose:()=>void;onSave:(o:Order)=>void}){
 const [pricing,setPricing]=useState<Pricing>(DEFAULT_PRICING);useEffect(()=>{fetch('/api/pricing').then(r=>r.json()).then(v=>setPricing(v as Pricing)).catch(()=>{})},[]);const calculatePrice=(p:number,q:number)=>priceFor(pricing,p,q);
 const [o,setO]=useState<Order>({...initial,notes:initial.notes||'',address:initial.address||'',tracking:initial.tracking||'',dueDate:initial.dueDate||'',priceNote:initial.priceNote||'',revisions:initial.revisions||0}),[tab,setTab]=useState('details'),[keep,setKeep]=useState(initial.images.map(i=>i.key)),[files,setFiles]=useState<{file:File;url:string;role:string}[]>([]),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[question,setQuestion]=useState(`היי ${initial.name}, כאן PARTYPRINT. יש לנו שאלה לגבי הזמנה ${initial.id.slice(0,8).toUpperCase()}: `),[showQuestion,setShowQuestion]=useState(false);const panel=useRef<HTMLDivElement>(null),upload=useRef<HTMLInputElement>(null),fileRef=useRef(files);
 useEffect(()=>{fileRef.current=files},[files]);useEffect(()=>()=>fileRef.current.forEach(f=>URL.revokeObjectURL(f.url)),[]);
 function close(){if(!dirty||confirm('יש שינויים שלא נשמרו. לצאת בלי לשמור?'))onClose()}
 useEffect(()=>{const prev=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.focus();return()=>{document.body.style.overflow=overflow;prev?.focus()}},[]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 function change<K extends keyof Order>(k:K,v:Order[K]){setO(old=>({...old,[k]:v}));setDirty(true);setSuccess('')}
 function changePack(p:number){change('package',p);change('quantity',packs[p].n);change('packageName',packs[p].name);change('price',calculatePrice(p,packs[p].n));change('priceNote','');change('shirts',Array.from({length:packs[p].n},(_,i)=>o.shirts[i]||{size:'',color:''}))}
 function quantity(n:number){if(!Number.isInteger(n)||n<1||n>100)return;change('quantity',n);change('shirts',Array.from({length:n},(_,i)=>o.shirts[i]||{size:'',color:''}));try{change('price',calculatePrice(o.package,n));change('priceNote','')}catch{}}
 function add(list:FileList|null){if(!list)return;const additions=Array.from(list);const err=imageUploadError([...files.map(f=>f.file),...additions]);if(err){setError(err);return}if(keep.length+files.length+additions.length>20){setError('עד 20 תמונות בהזמנה, כולל עיצובים.');return}setFiles(v=>[...v,...additions.map(file=>({file,url:URL.createObjectURL(file),role:'reference'}))]);setDirty(true);setError('');if(upload.current)upload.current.value=''}
 async function save(){
 const problem=!o.name.trim()?['details','שם הלקוח']:!whatsappLink(o.phone,'')?['details','טלפון / WhatsApp']:!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(o.email)?['details','כתובת מייל']:o.mode!=='lead'&&(o.shirts.length!==o.quantity||o.shirts.some(x=>!SIZES.includes(x.size as typeof SIZES[number])||!COLORS.includes(x.color as typeof COLORS[number])))?['shirts','בחרו מידה וצבע לכל חולצה']:null;
 if(problem){setTab(problem[0]);setError('לפני ששומרים: '+problem[1]);setTimeout(()=>{const target=Array.from(panel.current?.querySelectorAll<HTMLInputElement>('input,select')||[]).find(el=>problem[0]==='shirts'?!el.value:el.closest('label')?.textContent?.includes(problem[1]));target?.focus();target?.scrollIntoView({block:'center',behavior:'smooth'});target?.classList.add('needs-attention');setTimeout(()=>target?.classList.remove('needs-attention'),1800)},80);return}
 setBusy(true);setError('');setSuccess('');try{const f=new FormData();f.append('order',JSON.stringify({...o,keep,imageRoles:Object.fromEntries(o.images.map(i=>[i.key,i.role||"reference"]))}));for(const x of files){f.append('images',x.file);f.append('roles',x.role)}const saved=await api<Order>('/api/admin/orders/'+o.id,{method:'POST',body:f});setO({...saved,notes:saved.notes||'',address:saved.address||'',tracking:saved.tracking||'',dueDate:saved.dueDate||'',priceNote:saved.priceNote||''});setKeep(saved.images.map((i:{key:string})=>i.key));files.forEach(f=>URL.revokeObjectURL(f.url));setFiles([]);setDirty(false);setSuccess('כל השינויים נשמרו');onSave(saved)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function reload(){if(dirty&&!confirm('לטעון מחדש ולוותר על השינויים שלא נשמרו?'))return;setBusy(true);try{const fresh=await api<Order>('/api/admin/orders/'+o.id);setO({...fresh,notes:fresh.notes||'',address:fresh.address||'',tracking:fresh.tracking||'',dueDate:fresh.dueDate||'',priceNote:fresh.priceNote||''});setKeep(fresh.images.map((i:{key:string})=>i.key));files.forEach(f=>URL.revokeObjectURL(f.url));setFiles([]);setDirty(false);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function mail(){if(dirty){setError('יש לשמור את השינויים לפני שליחת המייל.');return}setBusy(true);setError('');try{const result=await api<{sent:boolean}>('/api/admin/orders/'+o.id+'/mail',{method:'POST'});if(!result.sent)throw Error('שירות הדיוור לא אישר את השליחה. נסו שוב בהמשך.');await reload();setSuccess('המייל התקבל בשירות השליחה ל־atzilul@gmail.com')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const index=Math.max(0,STAGES.findIndex(s=>s[0]===o.status));
 return <div className="editor-backdrop"><div className="order-editor" ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="editor-title" onKeyDown={e=>{if(e.key==='Escape'&&!busy)close();if(e.key==='Tab'){const items=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled)')||[]).filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus()}}}}>
 <header className="editor-header"><button className="studio-icon" onClick={close} disabled={busy} aria-label="חזרה להזמנות"><ArrowRight/></button><div><small>הזמנה <span dir="ltr">#{o.id.slice(0,8).toUpperCase()}</span> · {date(o.createdAt)}</small><h2 id="editor-title">{o.name}</h2></div><button className="studio-icon editor-refresh" disabled={busy} onClick={()=>void reload()} aria-label="טעינה מחדש"><RefreshCw size={19}/></button></header>
 <div className="editor-stage"><label>איפה ההזמנה עומדת?<select value={o.status} disabled={busy} onChange={e=>change('status',e.target.value)}>{STAGES.map(([s,l])=><option value={s} key={s}>{l}</option>)}</select></label><div className="stage-track" aria-label={'שלב '+(index+1)+' מתוך 7'}>{STAGES.map(([s,l],i)=><span title={l} key={s} className={i<=index?'done':''}>{i<index?<Check size={12}/>:i+1}</span>)}</div>{index<6&&<button className="next-stage" disabled={busy} onClick={()=>change('status',STAGES[index+1][0])}>השלב הבא: {STAGES[index+1][1]} <ChevronLeft size={16}/></button>}</div>
 <nav className="editor-tabs" aria-label="חלקי ההזמנה">{[['details','פרטי ההזמנה'],['shirts','חולצות ומחיר'],['images','תמונות ועיצובים'],['activity','טיפול והיסטוריה']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)} className={tab===key?'active':''}>{label}</button>)}</nav>
 <div className="editor-body"><fieldset disabled={busy} className="editor-fields">
 {tab==='details'&&<><div className="editor-section-title"><span>01</span><h3>האנשים מאחורי החולצות</h3></div><div className="editor-two"><label>שם הלקוח<input value={o.name} maxLength={100} onChange={e=>change('name',e.target.value)}/></label><label>טלפון / WhatsApp<input value={o.phone} dir="ltr" type="tel" onChange={e=>change('phone',e.target.value)}/></label></div><label>כתובת מייל<input value={o.email} type="email" dir="ltr" maxLength={150} onChange={e=>change('email',e.target.value)}/></label><div className="editor-two"><label>סוג פנייה<select value={o.mode} onChange={e=>{change('mode',e.target.value);if(e.target.value!=='lead'&&!o.shirts.length)change('shirts',Array.from({length:o.quantity},()=>({size:'',color:''})))}}><option value="order">הזמנה</option><option value="custom">הזמנה בהתאמה</option><option value="lead">התייעצות</option></select></label><label>מועד יעד שסוכם<input type="date" value={o.dueDate} onChange={e=>change('dueDate',e.target.value)}/></label></div><label>כתובת למשלוח<textarea rows={2} value={o.address} maxLength={500} onChange={e=>change('address',e.target.value)} placeholder="יישוב, רחוב, מספר, דירה והנחיות למסירה"/></label><div className="editor-section-title"><span>02</span><h3>הרעיון שנעצב להם</h3></div><label>בריף לעיצוב<textarea rows={6} value={o.brief} maxLength={3000} onChange={e=>change('brief',e.target.value)} placeholder="מי מצטלם? מה האירוע? מה הסגנון והכיתוב?"/></label></>}
 {tab==='shirts'&&<><div className="editor-section-title"><Shirt size={22}/><h3>חבילה, מידות וצבעים</h3></div><div className="editor-two"><label>חבילה<select value={o.package} onChange={e=>changePack(Number(e.target.value))}>{packs.map((p,i)=><option key={p.name} value={i}>{p.name}</option>)}</select></label><label>מספר חולצות{o.package===4?<select value={o.quantity} onChange={e=>quantity(Number(e.target.value))}>{[5,10,15,20].map(n=><option key={n}>{n}</option>)}</select>:<input type="number" min={packs[o.package].n} max={100} value={o.quantity} onChange={e=>quantity(Number(e.target.value))}/>}</label></div>{o.couponCode&&<p className="studio-note">קוד בעת ההזמנה: {o.couponCode} · הנחה מקורית: {money(o.discount||0)}. חישוב מחדש לפי חבילה אינו מפעיל את הקוד שוב.</p>}<div className="price-box"><label>מחיר ההזמנה (₪)<input type="number" step="0.01" min={0} max={100000} value={o.price} onChange={e=>change('price',Number(e.target.value))}/></label><button onClick={()=>{try{change('price',calculatePrice(o.package,o.quantity));change('priceNote','')}catch{setError('בחרו כמות מתאימה לחבילה.')}}}>חישוב לפי החבילה</button></div><label>הסבר להתאמת מחיר<textarea rows={2} value={o.priceNote} onChange={e=>change('priceNote',e.target.value)} placeholder="חובה אם המחיר שונה ממחיר החבילה" maxLength={500}/></label><label>סבבי תיקונים שבוצעו<input type="number" min={0} max={100} value={o.revisions} onChange={e=>change('revisions',Number(e.target.value))}/></label><p className="studio-note">סבב אחד כלול. {Math.max(0,(o.revisions||0)-1)} סבבים נוספים = {money(Math.max(0,(o.revisions||0)-1)*100)}. הסכום אינו נוסף למחיר אוטומטית.</p>{o.mode==='lead'?<p className="studio-banner">זו התייעצות. להעברה להזמנה ובחירת מידות, שנו את סוג הפנייה.</p>:<><button className="studio-text" onClick={()=>{if(!o.shirts[0]?.size||!o.shirts[0]?.color){setError('בחרו תחילה מידה וצבע לחולצה הראשונה.');return}change('shirts',o.shirts.map(()=>({...o.shirts[0]})))}}>החלת המידה והצבע של חולצה 1 על כולן</button><div className="admin-shirts">{o.shirts.map((s,i)=><div className="admin-shirt" key={i}><b>חולצה {i+1}</b><select aria-label={'מידה לחולצה '+(i+1)} value={s.size} onChange={e=>change('shirts',o.shirts.map((x,n)=>n===i?{...x,size:e.target.value}:x))}><option value="">בחרו מידה</option>{SIZES.map(s=><option key={s}>{s}</option>)}</select><select aria-label={'צבע לחולצה '+(i+1)} value={s.color} onChange={e=>change('shirts',o.shirts.map((x,n)=>n===i?{...x,color:e.target.value}:x))}><option value="">בחרו צבע</option>{COLORS.map(c=><option key={c} value={c}>{COLOR_LABELS[c]}</option>)}</select></div>)}</div></>}</>}
 {tab==='images'&&<><div className="editor-section-title"><ImagePlus/><h3>מרפרנס לעיצוב מוכן</h3></div><p className="studio-note">עד 20 תמונות להזמנה, 30MB בסך הכול. כל העלאה: עד 10 תמונות ועד 15MB, 5MB לתמונה. JPG, PNG או WEBP.</p><div className="admin-upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)add(e.dataTransfer.files)}}><input ref={upload} type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>add(e.target.files)} id="admin-images"/><label htmlFor="admin-images"><ImagePlus size={26}/><b>הוספת תמונות או עיצובים</b><span>אפשר גם לגרור קבצים לכאן</span></label></div><div className="admin-images">{o.images.filter(i=>keep.includes(i.key)).map(i=><div className="admin-image" key={i.key}><a href={`/api/admin/orders/${o.id}/image?key=${encodeURIComponent(i.key)}`} target="_blank" rel="noreferrer"><img src={`/api/admin/orders/${o.id}/image?key=${encodeURIComponent(i.key)}`} alt={i.name}/></a><p title={i.name}>{i.name}</p><select aria-label={'סוג התמונה '+i.name} value={i.role||'reference'} onChange={e=>change('images',o.images.map(x=>x.key===i.key?{...x,role:e.target.value}:x))}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={()=>{if(confirm('למחוק את התמונה מההזמנה? המחיקה תתבצע בשמירה.')){setKeep(v=>v.filter(k=>k!==i.key));setDirty(true)}}}><Trash2 size={16}/> הסרה</button></div>)}{files.map((f,i)=><div className="admin-image is-new" key={f.url}><img src={f.url} alt={f.file.name}/><p>{f.file.name}</p><select value={f.role} aria-label="סוג התמונה החדשה" onChange={e=>setFiles(v=>v.map((x,n)=>n===i?{...x,role:e.target.value}:x))}>{Object.entries(roles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={()=>{URL.revokeObjectURL(f.url);setFiles(v=>v.filter((_,n)=>n!==i))}}><X size={16}/> ביטול</button></div>)}</div>{keep.length<o.images.length&&<button className="studio-text" onClick={()=>setKeep(o.images.map(i=>i.key))}>ביטול הסרת התמונות</button>}<p className="studio-note">להחלפת תמונה: הסירו את הישנה והוסיפו את המתוקנת, ואז שמרו. ההורדה מהמייל תציג את התמונות שנשמרו לאחרונה.</p></>}
 {tab==='activity'&&<><div className="editor-section-title"><SlidersHorizontal/><h3>כל מה שצריך להמשך הטיפול</h3></div><label>הערות פנימיות<textarea rows={5} value={o.notes} maxLength={5000} onChange={e=>change('notes',e.target.value)} placeholder="תיאומים, דגשים למעצב, הערות להדפסה..."/></label><label>מספר מעקב / פרטי משלוח<input value={o.tracking} maxLength={500} onChange={e=>change('tracking',e.target.value)}/></label><div className="admin-mail"><Mail size={22}/><div><b>התראת המייל לסטודיו</b><p>{o.emailStatus==='accepted'?'שירות הדיוור קיבל את ההתראה. אין אישור קריאה.':o.emailStatus==='failed'?'שליחת ההתראה נכשלה.':'טרם נשלחה התראת מייל.'}</p></div><button onClick={()=>void mail()}>שליחה מחדש</button></div><div className="editor-section-title"><Clock/><h3>היסטוריית ההזמנה</h3></div><ol className="order-history">{[...(o.history||[])].reverse().map((h,i)=><li key={h.at+i}><span/><div><b>{h.action}</b><p>{new Date(h.at).toLocaleString('he-IL')} · {h.actor}</p></div></li>)}<li><span/><div><b>הפנייה נוצרה באתר</b><p>{new Date(o.createdAt).toLocaleString('he-IL')}</p></div></li></ol></>}
 </fieldset>
 <div className="editor-contact"><button onClick={()=>setShowQuestion(v=>!v)}><MessageCircle size={19}/> שאלה ללקוח בוואטסאפ</button><a href={`/api/admin/orders/${o.id}/bundle`} target="_blank" rel="noreferrer"><Download size={18}/> הורדת ההזמנה והקבצים שנשמרו</a></div>{showQuestion&&<div className="question-box"><label>ההודעה ללקוח<textarea rows={3} value={question} onChange={e=>setQuestion(e.target.value)} maxLength={2000}/></label><a className="whatsapp-action" href={whatsappLink(o.phone,question)||undefined} target="_blank" rel="noreferrer">פתיחת WhatsApp מול {o.name}<ArrowUpLeft size={18}/></a><small>ההודעה תיפתח לעריכה. השליחה מתבצעת על ידך בוואטסאפ.</small></div>}
 </div><footer className="editor-footer"><div aria-live="polite">{error?<p role="alert" className="studio-error">{error}</p>:success?<p className="save-success"><CheckCircle2 size={17}/>{success}</p>:<span>{dirty?'יש שינויים שלא נשמרו':'כל הפרטים מעודכנים'} · {money(o.price)}</span>}</div><button className="save-order" disabled={busy||!dirty} onClick={()=>void save()}>{busy?<LoaderCircle className="spin" size={19}/>:<Save size={19}/>} {busy?'שומרים…':'שמירת שינויים'}</button></footer></div></div>
}
