'use client';
/* eslint-disable react-hooks/exhaustive-deps -- ticket filters intentionally control the deferred loader. */
import {useEffect,useMemo,useRef,useState} from 'react';
import {AlertCircle,Check,Clock3,MessageCircle,Plus,RefreshCw,Search,Send,ShieldCheck,Tag,UserRound,Users,X} from 'lucide-react';
import {Ticket,TicketAssignee,TicketMessage,TICKET_PRIORITIES,TICKET_STATUSES,ticketPriorityLabel,ticketStatusLabel} from '@/lib/ticketing';

type TicketListing={tickets:Ticket[];total:number;counts:{status:string;n:number}[];urgent:number};
type TicketOrder={id:string;name:string;email:string;packageName:string;quantity:number;status:string;createdAt:string};
type Options={assignees:TicketAssignee[];orders:TicketOrder[]};
type Detail={ticket:Ticket;messages:TicketMessage[]};
type Draft={title:string;description:string;customerName:string;customerEmail:string;orderId:string;assigneeEmail:string;priority:string;dueAt:string};
const emptyDraft:Draft={title:'',description:'',customerName:'',customerEmail:'',orderId:'',assigneeEmail:'',priority:'normal',dueAt:''};
const statusTone:Record<string,string>={open:'חדש',in_progress:'בטיפול',waiting:'ממתין',done:'בוצע'};
async function api<T>(url:string,init?:RequestInit){const response=await fetch(url,init);const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||'לא ניתן להשלים את הפעולה.');return data as T}
function initials(value:string){return value.trim().split(/\s+/).map(word=>word[0]).join('').slice(0,2).toUpperCase()||'PP'}
function shortDate(value:string){return value?new Date(value).toLocaleDateString('he-IL',{day:'numeric',month:'short'}):''}
function dateTime(value:string){return value?new Date(value).toLocaleString('he-IL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):''}
function moneyDate(value:string){return value?new Date(value+'T12:00:00').toLocaleDateString('he-IL',{day:'numeric',month:'long'}):''}

export default function Tickets(){
 const [listing,setListing]=useState<TicketListing>({tickets:[],total:0,counts:[],urgent:0}),[options,setOptions]=useState<Options>({assignees:[],orders:[]}),[selectedId,setSelectedId]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[assignee,setAssignee]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[compose,setCompose]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[message,setMessage]=useState('');
 const searchRef=useRef<HTMLInputElement>(null);
 const activeDetail=detail?.ticket.id===selectedId?detail:null;
 const selected=activeDetail?.ticket||listing.tickets.find(ticket=>ticket.id===selectedId)||null;
 const mineCount=useMemo(()=>listing.tickets.filter(ticket=>ticket.assigneeEmail&&ticket.status!=='done').length,[listing.tickets]);
 async function load(){setLoading(true);setError('');try{const params=new URLSearchParams({q,status,priority,assignee});const data=await api<TicketListing>('/api/admin/tickets?'+params);setListing(data);if(!selectedId&&data.tickets[0])setSelectedId(data.tickets[0].id);if(selectedId&&!data.tickets.some(ticket=>ticket.id===selectedId))setSelectedId(data.tickets[0]?.id||'')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function loadOptions(){try{setOptions(await api<Options>('/api/admin/tickets/options'))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{const timer=setTimeout(()=>void load(),180);return()=>clearTimeout(timer)},[q,status,priority,assignee]);
 useEffect(()=>{let cancelled=false;api<Options>('/api/admin/tickets/options').then(data=>{if(!cancelled)setOptions(data)}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[]);
 useEffect(()=>{if(!selectedId)return;let cancelled=false;api<Detail>('/api/admin/tickets/'+encodeURIComponent(selectedId)).then(data=>{if(!cancelled)setDetail(data)}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[selectedId]);
 function chooseOrder(id:string){const order=options.orders.find(item=>item.id===id);setDraft(old=>({...old,orderId:id,customerName:order?.name||old.customerName,customerEmail:order?.email||old.customerEmail}))}
 function resetCompose(){setDraft(emptyDraft);setCompose(false)}
 function quickFilter(kind:'all'|'mine'|'urgent'|'open'){setQ('');if(kind==='all'){setStatus('');setPriority('');setAssignee('')}if(kind==='mine'){setStatus('');setPriority('');setAssignee('me')}if(kind==='urgent'){setStatus('');setPriority('urgent');setAssignee('')}if(kind==='open'){setStatus('open');setPriority('');setAssignee('')}}
 function announce(value:string){setNotice(value);window.setTimeout(()=>setNotice(old=>old===value?'':old),2600)}
 useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();searchRef.current?.focus()}if(event.key==='Escape'&&compose&&!busy)resetCompose()};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[compose,busy]);
 async function create(){if(!draft.title.trim()){setError('יש לתת לטיקט כותרת קצרה.');return}if(!draft.customerName.trim()||!draft.customerEmail.trim()){setError('יש לבחור הזמנה או למלא שם ומייל של לקוח.');return}setBusy(true);setError('');try{const result=await api<{ticket:Ticket}>('/api/admin/tickets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});resetCompose();setSelectedId(result.ticket.id);announce('הטיקט נפתח ונוסף לתיבת המשימות');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function update(patch:Record<string,unknown>){if(!selected||busy)return;setBusy(true);setError('');try{const result=await api<{ticket:Ticket}>('/api/admin/tickets/'+selected.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...patch,version:selected.version})});setDetail(old=>old?{...old,ticket:result.ticket}:old);setListing(old=>({...old,tickets:old.tickets.map(ticket=>ticket.id===result.ticket.id?{...ticket,...result.ticket}:ticket)}));announce('הטיקט עודכן')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function sendMessage(){if(!selected||!message.trim()||busy)return;setBusy(true);setError('');try{const result=await api<{message:TicketMessage}>('/api/admin/tickets/'+selected.id+'/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:message})});setDetail(old=>old?{ticket:{...old.ticket,updatedAt:result.message.createdAt,version:old.ticket.version+1},messages:[...old.messages,result.message]}:old);setMessage('');announce('העדכון נשלח לצוות');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const count=(key:string)=>listing.counts.find(item=>item.status===key)?.n||0;
 return <section className="tickets-page" dir="rtl">
  <header className="tickets-hero"><div><span className="tickets-eyebrow">TEAM INBOX · PARTYPRINT</span><h2>מרכז המשימות</h2><p>כל מה שצריך לזוז קדימה — מסודר לפי אנשים, הזמנות ודחיפות.</p></div><div className="tickets-hero-actions"><button className="tickets-refresh" onClick={()=>{void load();void loadOptions()}} aria-label="רענון טיקטים"><RefreshCw size={18}/></button><button className="ticket-primary" onClick={()=>{setError('');setDraft(emptyDraft);setCompose(true)}}><Plus size={18}/> טיקט חדש</button></div></header>
  <div className="ticket-metrics"><div className="ticket-metric metric-purple"><span>פתוחים</span><b>{count('open')+count('in_progress')+count('waiting')}</b><small>משימות פעילות</small></div><div className="ticket-metric metric-orange"><span>דחופים</span><b>{listing.urgent}</b><small>דורשים תשומת לב</small></div><div className="ticket-metric metric-cyan"><span>בטיפול הצוות</span><b>{mineCount}</b><small>משויכים לעובדים</small></div><div className="ticket-metric metric-green"><span>בוצעו</span><b>{count('done')}</b><small>נסגרו לאחרונה</small></div></div>
  {error&&<div className="ticket-error" role="alert"><AlertCircle size={18}/>{error}<button onClick={()=>setError('')} aria-label="סגירת הודעה"><X size={16}/></button></div>}{notice&&<div className="ticket-notice" role="status"><Check size={17}/>{notice}</div>}
  <div className="tickets-shell">
   <aside className="tickets-list-pane"><div className="tickets-list-head"><div><span className="tickets-eyebrow">WORKSPACE</span><h3>תיבת משימות <em>{listing.total}</em></h3></div><button className="tickets-plus" onClick={()=>{setDraft(emptyDraft);setCompose(true)}} aria-label="טיקט חדש"><Plus size={18}/></button></div>
    <label className="ticket-search"><Search size={17}/><input ref={searchRef} value={q} onChange={e=>setQ(e.target.value)} placeholder="חיפוש טיקט, לקוח או הזמנה"/><kbd>⌘ K</kbd></label>
    <div className="ticket-quick-filters" aria-label="סינון מהיר"><span>מהיר</span><button className={!status&&!priority&&!assignee?'is-active':''} onClick={()=>quickFilter('all')}>הכל</button><button className={assignee==='me'?'is-active':''} onClick={()=>quickFilter('mine')}>שלי</button><button className={priority==='urgent'?'is-active':''} onClick={()=>quickFilter('urgent')}>דחוף <b>{listing.urgent}</b></button><button className={status==='open'?'is-active':''} onClick={()=>quickFilter('open')}>חדש</button></div>
    <div className="ticket-filters"><select aria-label="סינון לפי סטטוס" value={status} onChange={e=>setStatus(e.target.value)}><option value="">כל הסטטוסים</option>{TICKET_STATUSES.map(item=><option key={item} value={item}>{ticketStatusLabel(item)}</option>)}</select><select aria-label="סינון לפי דחיפות" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">כל הדחיפויות</option>{TICKET_PRIORITIES.map(item=><option key={item} value={item}>{ticketPriorityLabel(item)}</option>)}</select><select aria-label="סינון לפי עובד" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">כל העובדים</option><option value="me">המשימות שלי</option>{options.assignees.map(item=><option key={item.email} value={item.email}>{item.name}</option>)}</select></div>
    <div className="ticket-list" aria-live="polite">{loading&&!listing.tickets.length?<div className="ticket-list-empty"><RefreshCw className="spin"/> טוענים משימות…</div>:!listing.tickets.length?<div className="ticket-list-empty"><MessageCircle size={30}/><b>אין כאן טיקטים</b><span>פתחו משימה חדשה והצוות יראה אותה מיד.</span><button className="ticket-link-button" onClick={()=>setCompose(true)}>פתיחת טיקט ראשון</button></div>:listing.tickets.map(ticket=><button key={ticket.id} className={'ticket-row '+(selectedId===ticket.id?'is-selected':'')} onClick={()=>setSelectedId(ticket.id)}><span className={'ticket-priority-dot priority-'+ticket.priority}/><div className="ticket-row-main"><div className="ticket-row-title"><b>{ticket.title}</b><span className={'ticket-status status-'+ticket.status}>{statusTone[ticket.status]}</span></div><p>{ticket.lastMessage||ticket.description||'אין עדיין הודעה'}</p><div className="ticket-row-meta"><span>{ticket.customerName}</span>{ticket.orderId&&<span dir="ltr">#{ticket.orderId.slice(0,8).toUpperCase()}</span>}<time>{shortDate(ticket.updatedAt)}</time></div></div></button>)}</div>
   </aside>
   <section className="ticket-detail-pane">{selected?<><header className="ticket-detail-head"><div className="ticket-detail-title"><span className={'ticket-big-dot priority-'+selected.priority}/><div><span className="tickets-eyebrow">TICKET · {selected.id.slice(0,8).toUpperCase()}</span><h3>{selected.title}</h3><p>נפתח {dateTime(selected.createdAt)} · על ידי {selected.createdByName}</p></div></div><div className="ticket-detail-actions"><select value={selected.status} disabled={busy} onChange={e=>void update({status:e.target.value})} aria-label="סטטוס הטיקט">{TICKET_STATUSES.map(item=><option key={item} value={item}>{ticketStatusLabel(item)}</option>)}</select><select value={selected.priority} disabled={busy} onChange={e=>void update({priority:e.target.value})} aria-label="דחיפות הטיקט">{TICKET_PRIORITIES.map(item=><option key={item} value={item}>{ticketPriorityLabel(item)}</option>)}</select></div></header>
    <div className="ticket-detail-scroll"><div className="ticket-context-grid"><div className="ticket-context-card customer-card"><span className="context-icon"><UserRound size={17}/></span><div><small>לקוח</small><b>{selected.customerName}</b><a href={'mailto:'+selected.customerEmail} dir="ltr">{selected.customerEmail}</a></div></div><div className="ticket-context-card"><span className="context-icon"><Tag size={17}/></span><div><small>הזמנה</small>{selected.orderId?<a className="ticket-order-link" href={'/admin?order='+encodeURIComponent(selected.orderId)}><b dir="ltr">#{selected.orderId.slice(0,8).toUpperCase()}</b><span>פתיחת הזמנה</span></a>:<b className="muted">לא משויך</b>}</div></div><label className="ticket-context-card context-select"><span className="context-icon"><Users size={17}/></span><span><small>אחראי/ת</small><select value={selected.assigneeEmail} disabled={busy} onChange={e=>void update({assigneeEmail:e.target.value})}><option value="">ללא שיוך</option>{options.assignees.map(item=><option key={item.email} value={item.email}>{item.name}</option>)}</select></span></label><div className="ticket-context-card"><span className="context-icon"><Clock3 size={17}/></span><div><small>יעד</small><b>{selected.dueAt?moneyDate(selected.dueAt):'ללא תאריך'}</b>{selected.dueAt&&new Date(selected.dueAt+'T23:59:59')<new Date()&&selected.status!=='done'&&<span className="overdue">עבר המועד</span>}</div></div></div>
     <div className="ticket-description"><div className="ticket-avatar avatar-purple">{initials(selected.createdByName)}</div><div><b>{selected.createdByName}</b><small>{dateTime(selected.createdAt)}</small><p>{selected.description||'הטיקט נפתח ללא תיאור. הוסיפו עדכון ראשון למטה.'}</p></div></div>
     <div className="ticket-thread"><div className="thread-divider"><span>שרשור המשימה</span></div>{activeDetail?.messages.length?activeDetail.messages.map(item=><div className="thread-message" key={item.id}><div className="ticket-avatar avatar-cyan">{initials(item.authorName)}</div><div><div className="thread-message-head"><b>{item.authorName}</b><small>{dateTime(item.createdAt)}</small></div><p>{item.body}</p></div></div>):<div className="thread-empty"><MessageCircle size={21}/><span>אין עדיין עדכונים. כתבו הודעה כדי לשתף את הצוות.</span></div>}</div>
    </div><form className="ticket-composer" onSubmit={e=>{e.preventDefault();void sendMessage()}}><div className="composer-avatar">{initials(selected.assigneeName||'PARTYPRINT')}</div><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="כתבו עדכון לצוות…" maxLength={5000}/><button disabled={!message.trim()||busy} aria-label="שליחת הודעה"><Send size={18}/></button></form>
   </>:<div className="ticket-detail-empty"><ShieldCheck size={48}/><h3>בחרו משימה כדי להתחיל</h3><p>כאן יופיעו פרטי הלקוח, ההזמנה, האחראי והשרשור הפנימי.</p><button className="ticket-primary" onClick={()=>setCompose(true)}><Plus size={18}/> פתיחת טיקט חדש</button></div>}</section>
  </div>
  {compose&&<div className="ticket-compose-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)resetCompose()}}><form className="ticket-compose-modal" onSubmit={e=>{e.preventDefault();void create()}}><header><div><span className="tickets-eyebrow">NEW WORK ITEM</span><h3>טיקט חדש</h3><p>פתחו משימה ברורה, שייכו אותה לאנשים הנכונים והמשיכו הלאה.</p></div><button type="button" className="tickets-close" onClick={resetCompose} aria-label="סגירת חלון"><X/></button></header><label>כותרת המשימה<input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="למשל: לשלוח סקיצה לאישור משפחת כהן" maxLength={160}/></label><label>מה צריך לקרות?<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="הוסיפו הקשר, דדליין או פרטים שהצוות צריך לדעת…" rows={4} maxLength={10000}/></label><div className="ticket-form-grid"><label>בחירת הזמנה<select value={draft.orderId} onChange={e=>chooseOrder(e.target.value)}><option value="">ללא הזמנה קיימת</option>{options.orders.map(order=><option key={order.id} value={order.id}>{order.name} · #{order.id.slice(0,8).toUpperCase()}</option>)}</select></label><label>אחראי/ת<select value={draft.assigneeEmail} onChange={e=>setDraft({...draft,assigneeEmail:e.target.value})}><option value="">ללא שיוך</option>{options.assignees.map(item=><option key={item.email} value={item.email}>{item.name}</option>)}</select></label><label>שם הלקוח<input value={draft.customerName} onChange={e=>setDraft({...draft,customerName:e.target.value})} placeholder="שם מלא" maxLength={120}/></label><label>מייל הלקוח<input type="email" dir="ltr" value={draft.customerEmail} onChange={e=>setDraft({...draft,customerEmail:e.target.value})} placeholder="name@example.com" maxLength={160}/></label><label>דחיפות<select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}>{TICKET_PRIORITIES.map(item=><option key={item} value={item}>{ticketPriorityLabel(item)}</option>)}</select></label><label>יעד<input type="date" value={draft.dueAt} onChange={e=>setDraft({...draft,dueAt:e.target.value})}/></label></div><p className="ticket-form-hint">בחירת הזמנה תמלא אוטומטית את פרטי הלקוח, ואפשר לעדכן אותם לפני יצירת הטיקט.</p>{draft.orderId&&<div className="selected-order-note"><Check size={16}/> הלקוח והפרטים נלקחו מההזמנה שנבחרה</div>}<div className="ticket-compose-footer"><button type="button" className="ticket-secondary" onClick={resetCompose}>ביטול</button><button type="submit" className="ticket-primary" disabled={busy}>{busy?<RefreshCw className="spin" size={17}/>:<Plus size={17}/>} יצירת טיקט</button></div></form></div>}
 </section>
}
