"use client";
/* eslint-disable @next/next/no-img-element -- staff previews use protected API URLs. */
/* eslint-disable react-hooks/exhaustive-deps -- initial workspace loading is intentionally deferred once. */
import Link from '@/components/safe-link';
import {useEffect,useRef,useState} from 'react';
import type {StaffJob} from '@/lib/staff-workspace';
import {imageUploadError} from '@/lib/upload-limits';
import {STAGES} from '@/lib/orders';
import ProfileEditor from './profile';
type WorkspaceData={role:string;orders:StaffJob[];more:boolean};
export default function Workspace(){
 const [data,setData]=useState<WorkspaceData|null>(null),[page,setPage]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[generation,setGeneration]=useState(0);
 const dirty=useRef(new Set<string>()),request=useRef(0);
 async function load(nextPage=page){const seq=++request.current;setLoading(true);setError('');try{const r=await fetch('/api/admin/workspace?page='+nextPage);if(!r.ok)throw Error('לא ניתן לטעון את המשימות. בדקו את החיבור וההרשאה ונסו שוב.');const value=await r.json() as WorkspaceData;if(seq!==request.current)return;dirty.current.clear();setData(value);setPage(nextPage);setGeneration(n=>n+1)}catch(e){if(seq===request.current)setError((e as Error).message)}finally{if(seq===request.current)setLoading(false)}}
 useEffect(()=>{const id=window.setTimeout(()=>void load(0),0);return()=>{window.clearTimeout(id);request.current++}},[]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty.current.size||busy){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave)},[busy]);
 function canLeave(){return !busy&&(!dirty.current.size||confirm('יש עבודה שלא נשמרה. להמשיך ולוותר על השינויים והקבצים שבחרתם?'))}
 function navigate(nextPage:number){if(canLeave())void load(nextPage)}
 return <main className="staff-workspace" dir="rtl"><header><Link href="/" onClick={e=>{if(!canLeave())e.preventDefault()}}>PARTYPRINT ✳</Link><h1>{data?.role==='printer'?'שולחן ההדפסה':'שולחן העיצוב'}</h1><p>המשימות שהוקצו לכם</p><div className="staff-toolbar"><button disabled={busy||loading} onClick={()=>navigate(page)}>רענון המשימות</button><a href="/signout-with-chatgpt?return_to=/admin" onClick={e=>{if(!canLeave())e.preventDefault()}}>יציאה</a></div></header><details className="staff-profile"><summary>הפרופיל שלי</summary><ProfileEditor compact/></details>{error&&<p className="studio-error" role="alert">{error}</p>}{loading&&<p role="status">טוענים את המשימות…</p>}{data?.orders.length===0&&<p>כרגע אין הזמנות שהוקצו לכם.</p>}{data?.orders.map(j=><JobCard key={generation+':'+j.id} job={j} role={data.role} disabled={busy||loading} onBusy={setBusy} onDirty={changed=>{if(changed)dirty.current.add(j.id);else dirty.current.delete(j.id)}} onSaved={updated=>setData(value=>value?{...value,orders:value.orders.map(o=>o.id===updated.id?updated:o)}:value)}/>)}<nav aria-label="עמודי משימות"><button disabled={!page||busy||loading} onClick={()=>navigate(page-1)}>הקודם</button><span>עמוד {page+1}</span><button disabled={!data?.more||busy||loading} onClick={()=>navigate(page+1)}>הבא</button></nav></main>
}
function JobCard({job:j,role,disabled,onBusy,onDirty,onSaved}:{job:StaffJob;role:string;disabled:boolean;onBusy:(v:boolean)=>void;onDirty:(v:boolean)=>void;onSaved:(j:StaffJob)=>void}){
 const [brief,setBrief]=useState(j.brief||''),[files,setFiles]=useState<File[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 const changed=brief!==(j.brief||'')||files.length>0;
 useEffect(()=>{onDirty(changed)},[changed]);
 function add(list:FileList|null){if(!list)return;const next=[...files];for(const file of Array.from(list))if(!next.some(f=>f.name===file.name&&f.size===file.size&&f.lastModified===file.lastModified))next.push(file);const issue=imageUploadError(next);if(issue){setError(issue);return}if((j.images?.length||0)+next.length>20){setError('אפשר לשמור עד 20 תמונות להזמנה. פנו למנהל להסרת קבצים שאינם נחוצים.');return}setFiles(next);setError('');setNotice('')}
 async function save(e:React.FormEvent){e.preventDefault();if(disabled||saving)return;if(role==='printer'&&!confirm('ההדפסה נבדקה ומוכנה? ההזמנה תסומן כהדפסה מוכנה.'))return;setSaving(true);onBusy(true);setError('');setNotice('');const form=new FormData();form.set('id',j.id);form.set('version',String(j.version));form.set('brief',brief);files.forEach(f=>form.append('images',f));try{const r=await fetch('/api/admin/workspace',{method:'POST',body:form});const value=await r.json().catch(()=>({})) as {error?:string;order?:StaffJob};if(!r.ok)throw Error(value.error||'לא ניתן לשמור. הפרטים והקבצים שבחרתם נשארו כאן.');if(!value.order)throw Error('לא התקבל אישור שמירה. רעננו את המשימות כדי לבדוק אם העדכון נקלט.');setFiles([]);setBrief(value.order.brief||'');onDirty(false);onSaved(value.order);setNotice(role==='printer'?'ההדפסה סומנה כמוכנה.':'הבריף והעיצובים נשמרו בהזמנה.')}catch(e){setError((e as Error).message)}finally{setSaving(false);onBusy(false)}}
 const date=j.taskDue?new Date(j.taskDue+'Z'):null;
 return <article className="settings-card staff-job"><div className="staff-job-heading"><h2>#{j.id.slice(0,8).toUpperCase()} · {j.quantity} חולצות</h2><span>{STAGES.find(([key])=>key===j.status)?.[1]||j.status}</span></div><p>{j.task||'טרם הוגדרה משימה'}{date&&Number.isFinite(date.getTime())&&' · '+date.toLocaleString('he-IL')}</p>{error&&<p className="studio-error" role="alert">{error}</p>}{notice&&<p className="staff-saved" role="status">{notice}</p>}<form onSubmit={e=>void save(e)}><fieldset className="editor-fields" disabled={disabled||saving}>{role==='printer'?<><p>{j.printNote}</p>{j.ready?<a href={'/api/admin/orders/'+j.id+'/print'}>הורדת תיק הדפסה מאושר</a>:<p>ממתינים לאישור עיצוב.</p>}<button className="save-order" disabled={!j.ready||j.status!=='printing'}>{saving?'שומרים…':j.status==='printed'?'ההדפסה מוכנה':'סימון ההדפסה כמוכנה'}</button></>:<><label>בריף לעיצוב<textarea name="brief" value={brief} onChange={e=>{setBrief(e.target.value);setNotice('')}} rows={5} maxLength={3000}/></label><div className="version-images">{j.images?.map(i=><a key={i.key} href={'/api/admin/workspace?id='+j.id+'&key='+encodeURIComponent(i.key)} target="_blank" rel="noreferrer"><img loading="lazy" src={'/api/admin/workspace?id='+j.id+'&key='+encodeURIComponent(i.key)} alt={i.name}/><span>{i.name}</span></a>)}</div><label>הוספת עיצובים<input type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{add(e.target.files);e.target.value=''}}/></label><small>עד 10 קבצים בהעלאה, 5MB לקובץ ו־15MB יחד. עד 20 תמונות ו־30MB בהזמנה כולה.</small>{files.length>0&&<div className="staff-pending"><b>{files.length} קבצים מוכנים לשמירה · {(files.reduce((n,f)=>n+f.size,0)/1024/1024).toFixed(1)}MB</b><ul>{files.map((f,i)=><li key={f.name+f.lastModified}><span>{f.name}<small>{(f.size/1024/1024).toFixed(1)}MB</small></span><button type="button" aria-label={'הסרת '+f.name} onClick={()=>setFiles(value=>value.filter((_,n)=>n!==i))}>הסרה</button></li>)}</ul></div>}<div className="staff-save-row"><button disabled={!changed} className="save-order">{saving?'שומרים את העיצוב…':'שמירת העיצוב והבריף'}</button>{changed&&<span>יש שינויים שלא נשמרו</span>}</div></>}</fieldset></form></article>
}
