import Link from '@/components/safe-link';
import type {Metadata} from 'next';
import {listBlogPosts} from '@/lib/blog';
import SeoFooterLinks from '@/components/seo-footer-links';
import BlogIndex from './blog-index';
import './blog.css';

export const metadata:Metadata={title:'בלוג PARTYPRINT | רעיונות למתנות, חולצות ואירועים',description:'מדריכים ורעיונות למתנות בעיצוב אישי, חולצות לימי הולדת, מסיבות רווקים, מסיבות רווקות וערבי צוות.',keywords:['בלוג מתנות בעיצוב אישי','רעיונות לחולצות יום הולדת','חולצה למסיבת רווקים','חולצה למסיבת רווקות','מתנה לערב צוות'],alternates:{canonical:'/blog',types:{'application/rss+xml':'/blog/feed.xml'}},openGraph:{title:'בלוג PARTYPRINT | רעיונות למתנות, חולצות ואירועים',description:'מדריכים ורעיונות למתנות בעיצוב אישי, חולצות לימי הולדת, מסיבות רווקים, מסיבות רווקות וערבי צוות.',url:'https://partyprint.co.il/blog',type:'website',images:[{url:'/party-crew.webp',alt:'חבורה בחולצות בעיצוב אישי של PARTYPRINT'}]}};
export const dynamic='force-dynamic';

export default async function BlogPage(){const posts=await listBlogPosts();const canonical='https://partyprint.co.il/blog';const schema={'@context':'https://schema.org','@graph':[{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'PARTYPRINT',item:'https://partyprint.co.il/'},{'@type':'ListItem',position:2,name:'בלוג',item:canonical}]},{'@type':'Blog','@id':canonical+'#blog',url:canonical,name:'בלוג PARTYPRINT',description:'מדריכים ורעיונות למתנות בעיצוב אישי, חולצות לימי הולדת, מסיבות, ערבי צוות ואירועים.',inLanguage:'he-IL',publisher:{'@id':'https://partyprint.co.il/#organization'},blogPost:posts.map(post=>({'@type':'BlogPosting',headline:post.title,url:canonical+'/'+post.slug,image:post.coverImage?`https://partyprint.co.il${post.coverImage}`:undefined,datePublished:post.publishedAt||post.createdAt,dateModified:post.updatedAt}))}]};return <main className="blog-page" dir="rtl"><BlogNav/><section className="blog-hero"><div className="blog-hero-inner"><span className="blog-kicker">PARTYPRINT / IDEAS TO WEAR</span><h1>רעיונות טובים<br/><span>נשארים איתכם.</span></h1><p>מדריכים קצרים שיעזרו לבחור מתנה, לבנות קונספט לאירוע ולהפוך תמונה או בדיחה לעיצוב אישי שאפשר ללבוש.</p></div></section><section className="blog-main"><div className="blog-section-head"><div><span className="blog-kicker">THE PARTYPRINT JOURNAL</span><h2>מה חוגגים הפעם?</h2></div><p>תוכן שימושי לפני שמזמינים: רעיונות, תכנון, מידות, תמונות וכל מה שעוזר להגיע לעיצוב שמרגיש באמת שלכם.</p></div><BlogIndex posts={posts}/></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><BlogFooter/></main>}
function BlogNav(){return <header className="blog-nav"><Link className="blog-brand" href="/" aria-label="PARTYPRINT — חזרה לאתר"/><nav className="blog-nav-links"><Link href="/">האתר הראשי</Link><Link href="/#packages">החבילות</Link><Link href="/#faq">שאלות נפוצות</Link></nav><Link className="blog-nav-cta" href="/#order">מתחילים בלי חיוב</Link></header>}
function BlogFooter(){return <footer className="blog-footer"><SeoFooterLinks/><div className="blog-footer-bottom"><strong>PARTYPRINT · אנשים אמיתיים. עיצובים לא רגילים.</strong><Link href="/">חזרה לאתר הראשי</Link></div></footer>}
