/* eslint-disable @next/next/no-img-element -- curated studio examples. */
import Link from '@/components/safe-link';
import type {Metadata} from 'next';
import {STUDIO_PAGES,STUDIO_PAGE_URL} from '@/lib/studio-pages';
import {SeoFooter,SeoNav} from '@/components/seo-layout';
import '../seo/seo.css';

export const metadata:Metadata={title:'דוגמאות ותהליכי עבודה | PARTYPRINT',description:'דוגמאות להדמיות עיצוב של PARTYPRINT למשפחות, מסיבות רווקים, מסיבות רווקות וערבי צוות — מהרעיון ועד החולצה.',keywords:['דוגמאות חולצות בעיצוב אישי','תהליך עיצוב חולצה','חולצות למסיבת רווקים','חולצות למסיבת רווקות','חולצה לערב צוות'],alternates:{canonical:'/work'},openGraph:{title:'דוגמאות ותהליכי עבודה | PARTYPRINT',description:'דוגמאות להדמיות עיצוב של PARTYPRINT למשפחות, מסיבות רווקים, מסיבות רווקות וערבי צוות.',url:'https://partyprint.co.il/work',type:'website',images:[{url:'/party-crew.webp',alt:'דוגמת עיצוב לחבורה בחולצות PARTYPRINT'}]}};

export default function WorkPage(){
 const canonical='https://partyprint.co.il/work';
 const schema={'@context':'https://schema.org','@graph':[{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'PARTYPRINT',item:'https://partyprint.co.il/'},{'@type':'ListItem',position:2,name:'דוגמאות ותהליכי עבודה',item:canonical}]},{'@type':'CollectionPage','@id':canonical+'#collection',url:canonical,name:'דוגמאות ותהליכי עבודה | PARTYPRINT',description:'דוגמאות להדמיות עיצוב של PARTYPRINT למשפחות, מסיבות וערבי צוות.',inLanguage:'he-IL',isPartOf:{'@id':'https://partyprint.co.il/#website'},mainEntity:{'@type':'ItemList',numberOfItems:STUDIO_PAGES.length,itemListElement:STUDIO_PAGES.map((item,index)=>({'@type':'ListItem',position:index+1,name:item.title,url:'https://partyprint.co.il'+STUDIO_PAGE_URL(item.slug)}))}}]};
 return <main className="seo-page" dir="rtl"><SeoNav/><section className="seo-work-hero"><div><span className="seo-kicker">PARTYPRINT / STUDIO EXAMPLES</span><h1>ככה רעיון<br/><span>מקבל צורה.</span></h1><p>אלו הדמיות כיוון שמראות איך אנחנו חושבים: מהסיפור, דרך התמונות והבריף, ועד שפה שאפשר ללבוש. הן לא מוצרים של לקוחות ולא מבטיחות תוצאה זהה.</p><Link className="seo-primary-cta" href="/#order">ליצור את הגרסה שלכם <span aria-hidden="true">←</span></Link></div><div className="seo-work-hero-note"><strong>השראה, לא קטלוג.</strong><span>כל עיצוב חדש נבנה לפי האנשים והאירוע שלכם.</span></div></section><section className="seo-work-content"><div className="seo-section-heading"><div><span className="seo-kicker">FROM IDEA TO SHIRT</span><h2>בוחרים כיוון<br/>ומתחילים לדבר.</h2></div><p>כל דוגמה מפרקת את ההחלטות שעוזרות לעיצוב לעבוד: רעיון אחד, תמונות ברורות, התאמה לקבוצה ואישור לפני הדפסה.</p></div><div className="seo-work-grid">{STUDIO_PAGES.map(item=><Link className="seo-work-card" href={STUDIO_PAGE_URL(item.slug)} key={item.slug}><div className="seo-work-card-image"><img src={item.heroImage} width="1254" height="1254" alt={item.heroAlt} loading="lazy"/><span>הדמיית עיצוב</span></div><div><span className="seo-kicker">{item.kicker}</span><h2>{item.title}</h2><p>{item.intro}</p><strong>לפרטי התהליך <span aria-hidden="true">↗</span></strong></div></Link>)}</div><section className="seo-work-method"><div><span className="seo-kicker">THE METHOD</span><h2>מה הופך כיוון<br/><span>לעיצוב שלכם?</span></h2></div><ol><li><strong>פרט שאי אפשר להעתיק</strong><span>משפט, תמונה, תחביב או בדיחה שמזוהים עם האנשים.</span></li><li><strong>שפה אחת ברורה</strong><span>סגנון, צבעים והיררכיה שעובדים גם בקבוצה וגם בתמונה.</span></li><li><strong>אישור לפני ייצור</strong><span>משתפים אתכם בכיוון ומדייקים לפני ההדפסה.</span></li></ol></section></section><p className="seo-editorial-note">כל התמונות בעמוד זה מסומנות כהדמיות עיצוב. הן נועדו להמחיש כיוונים אפשריים ולא להציג הזמנות של לקוחות.</p><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><SeoFooter/></main>;
}
