'use client';
import {useEffect,useState} from 'react';
import {Upload,Plus,X,Check} from 'lucide-react';
import {imageUploadError,MAX_IMAGES,MAX_IMAGE_TOTAL_BYTES} from '@/lib/upload-limits';
function Preview({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u)},[file]);return url?<img src={url} alt={file.name}/>:null}
export function ReferenceUpload({files,onChange,disabled}:{files:File[];onChange:(files:File[])=>void;disabled:boolean}){
 const [quality,setQuality]=useState<string[]>([]);useEffect(()=>{let cancelled=false;Promise.all(files.map(async file=>{try{const bitmap=await createImageBitmap(file);const small=Math.min(bitmap.width,bitmap.height)<800;const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx){bitmap.close();return ''}ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const {data}=ctx.getImageData(0,0,canvas.width,canvas.height);let sum=0,count=0;for(let i=4;i<data.length;i+=4){sum+=Math.abs(data[i]-data[i-4]);count++}return small?file.name+': הרזולוציה נמוכה יחסית. עדיף לצרף מקור גדול וברור.':sum/Math.max(count,1)<4?file.name+': מעט פרטים זוהו בתמונה. כדאי לבדוק שהיא חדה ולא מטושטשת.':''}catch{return file.name+': לא הצלחנו לבדוק תצוגה מקדימה. בדקו שהקובץ נפתח אצלכם.'}})).then(v=>{if(!cancelled)setQuality(v.filter(Boolean))});return()=>{cancelled=true}},[files]);const [error,setError]=useState(''),[notice,setNotice]=useState('');const total=files.reduce((sum,f)=>sum+f.size,0);
 function add(incoming:File[]){if(!incoming.length)return;const next=[...files];for(const file of incoming){if(!next.some(f=>f.name===file.name&&f.size===file.size&&f.lastModified===file.lastModified))next.push(file)}const issue=imageUploadError(next);if(issue){setError(issue);setNotice('');return}onChange(next);setError('');setNotice(next.length===files.length?'התמונות האלו כבר נמצאות בבחירה.':`${next.length-files.length} תמונות נוספו. אפשר להוסיף עוד בכל רגע.`)}
 return <div className="reference-upload"><div className="upload-count"><strong>התמונות שלכם, ההשראה שלנו</strong><span>{files.length}/{MAX_IMAGES}</span></div><p>אפשר לבחור כמה תמונות יחד, או להוסיף אחת בכל פעם.</p><label className={'reference-add '+(disabled||files.length>=MAX_IMAGES?'disabled':'')}><Upload size={24}/><strong>{files.length?'הוספת תמונות נוספות':'בחירת תמונות מהטלפון'}</strong><span>JPG, PNG, WEBP · עד 5MB לתמונה · 15MB בסך הכול</span><input disabled={disabled||files.length>=MAX_IMAGES} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{add(Array.from(e.target.files||[]));e.target.value=''}}/></label>{files.length>0&&<><div className="reference-grid">{files.map((f,i)=><div className="reference-tile" key={f.name+f.size+f.lastModified}><Preview file={f}/><span className="reference-index">{i+1}</span><button type="button" disabled={disabled} aria-label={'הסרת '+f.name} onClick={()=>{onChange(files.filter((_,n)=>n!==i));setError('');setNotice('התמונה הוסרה.')}}><X size={18}/></button><span className="reference-name" title={f.name}>{f.name}</span></div>)}</div><div className="upload-storage"><span>{(total/1024/1024).toFixed(1)} מתוך 15MB</span><progress aria-label="נפח התמונות שנבחרו" value={total} max={MAX_IMAGE_TOTAL_BYTES}/></div><p className="reference-receipt"><Check size={16}/> כל {files.length} התמונות ייכללו בקובץ ההזמנה המרוכז.</p></>}{quality.length>0&&<div className="quality-notice" role="status"><b>רגע לפני שמעצבים</b>{quality.map(t=><p key={t}>{t}</p>)}<small>בדיקה ראשונית בלבד. הצוות יבדוק התאמה לעיצוב ולהדפסה.</small></div>}{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="upload-feedback" role="status">{notice}</p>}<p className="fine">אפשר גם בלי תמונות כרגע, ולהשלים אותן ב־WhatsApp.</p></div>
}
