'use client';
import {useState} from 'react';
import {Check,MessageCircle,Download,Copy} from 'lucide-react';
export function WhatsAppOrder({id,summary,images,onReset,emailSent,trackingUrl}:{trackingUrl?:string;emailSent:boolean;id:string;summary:string;images:File[];onReset:()=>void}){
 const [copyNotice,setCopyNotice]=useState(''),[copyFallback,setCopyFallback]=useState('');
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setCopyFallback('');setCopyNotice(label+' הועתק.')}catch{setCopyFallback(value);setCopyNotice('לא ניתן להעתיק אוטומטית. לחצו על השדה כדי לסמן ולהעתיק ידנית.')}}
 function download(){const url=URL.createObjectURL(new Blob(['\uFEFF',summary],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`PARTYPRINT-${id.slice(0,8)}.txt`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
 const accepted=emailSent;
 return <div className="whatsapp-handoff"><span className="wa-ready"><Check size={22}/> הבקשה נשמרה</span><h3>הרעיון שלכם בפנים.</h3><p>כל פרטי ההזמנה ו־{images.length} התמונות נשמרו עם מספר הפנייה שלכם.</p><div className="wa-reference">מספר פנייה <b dir="ltr">{id.slice(0,8).toUpperCase()}</b><button type="button" aria-label="העתקת מספר הפנייה" onClick={()=>void copy(id.slice(0,8).toUpperCase(),'מספר הפנייה')}><Copy size={16}/></button></div>{accepted?<p className="wa-notice" role="status">ההזמנה נמצאת במערכת הניהול של הסטודיו. ניצור איתכם קשר להמשך טיפול.</p>:<p className="wa-notice" role="status">ההזמנה נמצאת במערכת הניהול של הסטודיו. התראת המייל טרם נשלחה, אבל אין צורך למלא את הטופס שוב.</p>}<p className="fine">אישור שמירה אינו אישור תשלום או מועד אספקה. אישור שירות השליחה אינו אישור שההודעה נקראה.</p><>{trackingUrl&&<a className="cta orange-bg" href={trackingUrl}>למעקב אחר ההזמנה שלכם ↗</a>}</>{trackingUrl&&<button type="button" className="wa-file-button" onClick={()=>void copy(trackingUrl,'קישור המעקב')}><Copy size={18}/> העתקת קישור המעקב</button>}{copyNotice&&<p role="status" className="wa-copy-notice">{copyNotice}</p>}{copyFallback&&<input className="wa-copy-fallback" aria-label="פרטים להעתקה ידנית" dir="ltr" readOnly value={copyFallback} onFocus={e=>e.target.select()}/>}<button type="button" className="wa-file-button" onClick={download}><Download size={18}/> שמירת סיכום לעצמכם</button><a className="text-link" href={'https://wa.me/972552896236?text='+encodeURIComponent('היי, יש לי שאלה לגבי פנייה '+id)} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/> שאלה לסטודיו</a><button type="button" className="wa-reset" onClick={onReset}>יצירת פנייה נוספת</button></div>
}
