import {bindings} from './order-store';
import {BLOG_SEED_POSTS,BlogFaq,BlogLink,BlogSeed} from './blog-seed';

export type BlogPost=BlogSeed&{status:'draft'|'published';author:string;publishedAt:string|null;createdAt:string;updatedAt:string;version:number};
type BlogRow={id:string;slug:string;status:string;title:string;excerpt:string;content:string;cover_image:string;cover_alt:string;inline_image_1:string;inline_image_1_alt:string;inline_image_2:string;inline_image_2_alt:string;seo_title:string;seo_description:string;keywords:string;faqs:string;internal_links:string;author:string;published_at:string|null;created_at:string;updated_at:string;version:number};
const json=<T,>(value:string,fallback:T):T=>{try{return JSON.parse(value) as T}catch{return fallback}};
const safeStatus=(value:unknown):'draft'|'published'=>value==='published'?'published':'draft';
export function rowToBlog(row:BlogRow):BlogPost{return {id:row.id,slug:row.slug,status:safeStatus(row.status),title:row.title,excerpt:row.excerpt,content:row.content,coverImage:row.cover_image,coverAlt:row.cover_alt,inlineImage1:row.inline_image_1,inlineImage1Alt:row.inline_image_1_alt,inlineImage2:row.inline_image_2,inlineImage2Alt:row.inline_image_2_alt,seoTitle:row.seo_title,seoDescription:row.seo_description,keywords:json<string[]>(row.keywords,[]),faqs:json<BlogFaq[]>(row.faqs,[]),internalLinks:json<BlogLink[]>(row.internal_links,[]),author:row.author,publishedAt:row.published_at,createdAt:row.created_at,updatedAt:row.updated_at,version:Number(row.version)}};
export function blogValues(post:Partial<BlogPost>&BlogSeed){return [post.id,post.slug,safeStatus(post.status),post.title,post.excerpt,post.content,post.coverImage,post.coverAlt,post.inlineImage1,post.inlineImage1Alt,post.inlineImage2,post.inlineImage2Alt,post.seoTitle,post.seoDescription,JSON.stringify(post.keywords),JSON.stringify(post.faqs),JSON.stringify(post.internalLinks),post.author||'PARTYPRINT',post.publishedAt||null,post.createdAt,post.updatedAt,post.version||1]}
export async function ensureBlogSeed(){const db=bindings().DB;const existing=await db.prepare('SELECT id FROM blog_posts').all<{id:string}>();const known=new Set(existing.results.map(row=>row.id));const missing=BLOG_SEED_POSTS.filter(post=>!known.has(post.id));if(!missing.length)return;const now=new Date().toISOString();await db.batch(missing.map(post=>db.prepare('INSERT OR IGNORE INTO blog_posts (id,slug,status,title,excerpt,content,cover_image,cover_alt,inline_image_1,inline_image_1_alt,inline_image_2,inline_image_2_alt,seo_title,seo_description,keywords,faqs,internal_links,author,published_at,created_at,updated_at,version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(...blogValues({...post,author:'PARTYPRINT',publishedAt:now,createdAt:now,updatedAt:now,version:1,status:'published'}))));}
export async function listBlogPosts(includeDraft=false){await ensureBlogSeed();const query=includeDraft?'SELECT * FROM blog_posts ORDER BY COALESCE(published_at,updated_at) DESC':'SELECT * FROM blog_posts WHERE status=? ORDER BY published_at DESC,updated_at DESC';const rows=includeDraft?await bindings().DB.prepare(query).all<BlogRow>():await bindings().DB.prepare(query).bind('published').all<BlogRow>();return rows.results.map(rowToBlog)}
export async function getBlogPost(slug:string,includeDraft=false){await ensureBlogSeed();const query=includeDraft?'SELECT * FROM blog_posts WHERE slug=?':'SELECT * FROM blog_posts WHERE slug=? AND status=?';const row=includeDraft?await bindings().DB.prepare(query).bind(slug).first<BlogRow>():await bindings().DB.prepare(query).bind(slug,'published').first<BlogRow>();return row?rowToBlog(row):null}
export function validateBlogPost(input:Partial<BlogPost>){const title=String(input.title||'').trim(),slug=String(input.slug||'').trim().toLowerCase(),excerpt=String(input.excerpt||'').trim(),content=String(input.content||'').trim();if(!title||title.length>160)throw Error('כותרת הפוסט חייבת להיות באורך 1 עד 160 תווים.');if(!/^[\u0590-\u05ffa-z0-9]+(?:-[\u0590-\u05ffa-z0-9]+)*$/.test(slug)||slug.length>180)throw Error('ה-slug צריך להכיל אותיות, מספרים ומקפים בלבד.');if(!excerpt||excerpt.length>320)throw Error('נדרש תקציר קצר עד 320 תווים.');if(!content||content.length>40000)throw Error('נדרש תוכן לפוסט עד 40,000 תווים.');const faqs=Array.isArray(input.faqs)?input.faqs.filter(v=>v&&typeof v==='object').map(v=>({question:String((v as BlogFaq).question||'').trim(),answer:String((v as BlogFaq).answer||'').trim()})).filter(v=>v.question&&v.answer):[];if(faqs.length!==10)throw Error('בכל פוסט נדרשות בדיוק 10 שאלות ותשובות.');const internalLinks=Array.isArray(input.internalLinks)?input.internalLinks.filter(v=>v&&typeof v==='object').map(v=>({label:String((v as BlogLink).label||'').trim(),href:String((v as BlogLink).href||'').trim()})).filter(v=>v.label&&/^\//.test(v.href)).slice(0,8):[];return {...input,title,slug,excerpt,content,coverImage:String(input.coverImage||''),coverAlt:String(input.coverAlt||'').trim(),inlineImage1:String(input.inlineImage1||''),inlineImage1Alt:String(input.inlineImage1Alt||'').trim(),inlineImage2:String(input.inlineImage2||''),inlineImage2Alt:String(input.inlineImage2Alt||'').trim(),seoTitle:String(input.seoTitle||title).trim().slice(0,180),seoDescription:String(input.seoDescription||excerpt).trim().slice(0,320),keywords:Array.isArray(input.keywords)?input.keywords.map(v=>String(v).trim()).filter(Boolean).slice(0,30):[],faqs,internalLinks,status:safeStatus(input.status),author:String(input.author||'PARTYPRINT').trim().slice(0,100)||'PARTYPRINT'} as Partial<BlogPost>}
