import {publicOrigin} from '#partyprint-runtime';
import {Order,whatsappLink,stageLabel} from './orders';
import {orderSummary} from './order-summary';
type MailEnv={RESEND_API_KEY?:string;MAIL_FROM?:string};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function notifyOrder(env:MailEnv,order:Order,bundleUrl:string,attempt='initial'){
 if(!env.RESEND_API_KEY||!env.MAIL_FROM)return false;
 const wa=whatsappLink(order.phone,`היי ${order.name}, כאן PARTYPRINT. אנחנו מטפלים בהזמנה ${order.id.slice(0,8).toUpperCase()} ונשמח להמשיך איתך כאן.`);
 const admin=`${publicOrigin()}/admin?order=${order.id}`;
 const summary=orderSummary(order);
 const text=summary+'\n\nהמשך טיפול בוואטסאפ: '+wa+'\nהורדת פרטי ההזמנה והתמונות (קישור ל־30 יום): '+bundleUrl+'\nניהול ההזמנה: '+admin;
 const button=(url:string,label:string,color:string)=>`<a href="${escape(url)}" style="display:inline-block;background:${color};color:white;padding:14px 20px;border-radius:12px;text-decoration:none;font-weight:bold;margin:6px 0">${label}</a>`;
 const html=`<div dir="rtl" style="font-family:Arial,sans-serif;background:#f3f4f8;padding:24px;color:#18202c"><div style="max-width:640px;margin:auto;background:white;padding:28px;border-radius:20px"><h1 style="direction:ltr;text-align:right">PARTYPRINT ✳</h1><h2>הזמנה חדשה מ${escape(order.name)}</h2><p>${escape(order.packageName)} · ${order.quantity} חולצות · ${order.price} ₪</p><p>סטטוס: ${escape(stageLabel(order.status))}</p>${button(wa,'המשך טיפול בוואטסאפ','#147b46')}<br/>${button(bundleUrl,'הורדת פרטי ההזמנה וכל התמונות','#302450')}<p style="color:#667085">קובץ ZIP עם סיכום ותמונות. הקישור בתוקף ל־30 יום, מאפשר גישה למחזיק בו ומציג את פרטי ההזמנה העדכניים.</p>${button(admin,'פתיחת ההזמנה במערכת הניהול','#18202c')}<pre style="font-family:Arial,sans-serif;white-space:pre-wrap;line-height:1.8">${escape(summary)}</pre></div></div>`;
 try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`partyprint/${order.id}/${attempt}`},body:JSON.stringify({from:env.MAIL_FROM,to:['atzilul@gmail.com'],reply_to:order.email,subject:`PARTYPRINT · ${order.name} · ${order.id.slice(0,8)}`,text,html}),signal:AbortSignal.timeout(15000)});if(!response.ok){console.error('Order mail rejected',response.status);return false}return true}catch{console.error('Order mail unavailable');return false}
}

export async function notifyCustomer(env:MailEnv,order:Order,url:string,attempt='initial'){
 if(!env.RESEND_API_KEY||!env.MAIL_FROM)return false;const text=`היי ${order.name}, בקשת ההזמנה ${order.id.slice(0,8).toUpperCase()} נשמרה ב־PARTYPRINT.\n${order.quantity} חולצות · ${order.price} ₪\nכל ${order.images.length} התמונות נשמרו.\nמעקב אחר ההזמנה (קישור פרטי ל־90 יום): ${url}\nאין חיוב בשליחת הטופס. מועד האספקה ייקבע איתכם לפני העבודה.\nכולל עיצוב משותף וסבב תיקונים אחד; סבב נוסף 100 ₪.\nשאלה? https://wa.me/972552896236`;try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`partyprint/customer/${order.id}/${attempt}`},body:JSON.stringify({from:env.MAIL_FROM,to:[order.email],reply_to:'atzilul@gmail.com',subject:'PARTYPRINT · קיבלנו את הרעיון שלכם',text,html:`<div dir="rtl" style="font-family:Arial;padding:24px;line-height:1.8"><h1>הרעיון שלכם בפנים ✳</h1><p>${escape(text).replace(/\n/g,'<br/>')}</p><a href="${escape(url)}" style="display:inline-block;background:#352051;color:white;padding:16px;border-radius:12px">למעקב אחר ההזמנה</a></div>`}),signal:AbortSignal.timeout(15000)});return r.ok}catch{return false}}
