import {getChatGPTUser} from '@/app/chatgpt-auth';
import {approvalCurrent} from './production';
import {env} from 'cloudflare:workers';
import type {Coupon} from './pricing';
import {normalizeOrder,Order} from './orders';
export function bindings(){return env as unknown as {DB:D1Database;BUCKET:R2Bucket;RESEND_API_KEY?:string;MAIL_FROM?:string}}
export async function getOrder(id:string){const row=await bindings().DB.prepare('SELECT data,version FROM orders WHERE id=?').bind(id).first<{data:string;version:number}>();return row?{...normalizeOrder(JSON.parse(row.data)),version:row.version} as Order:null}
export async function insertOrder(o:Order,coupon?:Coupon|null){const n=normalizeOrder(o),db=bindings().DB;const args=[n.id,n.status,n.createdAt,n.createdAt,JSON.stringify(n)];if(coupon){const result=await db.batch([db.prepare("UPDATE coupons SET used=used+1 WHERE code=? AND version=? AND (json_extract(data,'$.maxUses')=0 OR used<json_extract(data,'$.maxUses'))").bind(coupon.code,coupon.version),db.prepare('INSERT INTO orders (id,status,created_at,updated_at,version,data) SELECT ?,?,?,?,1,? WHERE changes()=1').bind(...args)]);if(!result[1].meta.changes)throw Error('coupon_unavailable')}else await db.prepare('INSERT INTO orders (id,status,created_at,updated_at,version,data) VALUES (?,?,?,?,1,?)').bind(...args).run();return n}
export async function saveOrder(o:Order,version:number,action:string,actor:string){if(actor==='מנהל'){const user=await getChatGPTUser();actor=user?.email||actor}if(o.approval&&!approvalCurrent(o)){o={...o,approval:{...o.approval,state:'stale'},status:['review','approved','printing','printed'].includes(o.status)?'designing':o.status};action+=' · אישור העיצוב בוטל בעקבות שינוי בקבצים או בחולצות'}const updatedAt=new Date().toISOString();const previous=await getOrder(o.id);if(previous&&previous.status!==o.status)o={...o,stageHistory:[...(o.stageHistory||[]),{status:o.status,at:updatedAt}]};const n={...o,version:version+1,updatedAt,history:[...(o.history||[]),{at:updatedAt,action,actor}].slice(-300)};const result=await bindings().DB.prepare('UPDATE orders SET status=?,updated_at=?,version=version+1,data=? WHERE id=? AND version=? RETURNING id').bind(n.status,updatedAt,JSON.stringify(n),o.id,version).first();if(!result)throw Error('conflict');return n}
