import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const formRateLimits=sqliteTable('form_rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:integer('expires_at').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),status:text('status').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1),data:text('data').notNull()},t=>[index('orders_status_created').on(t.status,t.createdAt),index('orders_created').on(t.createdAt)]);
export const studioSettings=sqliteTable('studio_settings',{key:text('key').primaryKey(),version:integer('version').notNull().default(1),data:text('data').notNull()});
export const coupons=sqliteTable('coupons',{code:text('code').primaryKey(),version:integer('version').notNull().default(1),used:integer('used').notNull().default(0),data:text('data').notNull()});
export const siteEvents=sqliteTable('site_events',{key:text('key').primaryKey(),day:text('day').notNull(),kind:text('kind').notNull(),count:integer('count').notNull().default(0)},t=>[index('site_events_day').on(t.day)]);
export const tickets=sqliteTable('tickets',{id:text('id').primaryKey(),title:text('title').notNull(),description:text('description').notNull().default(''),status:text('status').notNull().default('open'),priority:text('priority').notNull().default('normal'),customerName:text('customer_name').notNull().default(''),customerEmail:text('customer_email').notNull().default(''),orderId:text('order_id'),assigneeEmail:text('assignee_email'),assigneeName:text('assignee_name'),createdByEmail:text('created_by_email').notNull(),createdByName:text('created_by_name').notNull(),dueAt:text('due_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('tickets_status_updated').on(t.status,t.updatedAt),index('tickets_assignee_status').on(t.assigneeEmail,t.status),index('tickets_order').on(t.orderId)]);
export const ticketMessages=sqliteTable('ticket_messages',{id:text('id').primaryKey(),ticketId:text('ticket_id').notNull(),authorEmail:text('author_email').notNull(),authorName:text('author_name').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('ticket_messages_ticket_created').on(t.ticketId,t.createdAt)]);
export const blogPosts=sqliteTable('blog_posts',{id:text('id').primaryKey(),slug:text('slug').notNull(),status:text('status').notNull().default('draft'),title:text('title').notNull(),excerpt:text('excerpt').notNull().default(''),content:text('content').notNull().default(''),coverImage:text('cover_image').notNull().default(''),coverAlt:text('cover_alt').notNull().default(''),inlineImage1:text('inline_image_1').notNull().default(''),inlineImage1Alt:text('inline_image_1_alt').notNull().default(''),inlineImage2:text('inline_image_2').notNull().default(''),inlineImage2Alt:text('inline_image_2_alt').notNull().default(''),seoTitle:text('seo_title').notNull().default(''),seoDescription:text('seo_description').notNull().default(''),keywords:text('keywords').notNull().default('[]'),faqs:text('faqs').notNull().default('[]'),internalLinks:text('internal_links').notNull().default('[]'),author:text('author').notNull().default('PARTYPRINT'),publishedAt:text('published_at'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),version:integer('version').notNull().default(1)},t=>[index('blog_posts_status_published').on(t.status,t.publishedAt),index('blog_posts_updated').on(t.updatedAt)]);
