import {guard,PRIVATE_HEADERS,adminError} from '@/lib/admin-auth';
import {getOrder,saveOrder,bindings} from '@/lib/order-store';
import {getPricing} from '@/lib/studio-settings';
import {editOrder,stageLabel} from '@/lib/orders';
import {readLimitedForm,validImage} from '@/lib/order-security';
import {imageUploadError} from '@/lib/upload-limits';
type Context={params:Promise<{id:string}>};
export async function GET(request:Request,{params}:Context){const denied=await guard();if(denied)return denied;try{const o=await getOrder((await params).id);return Response.json(o||{error:'ההזמנה לא נמצאה.'},{status:o?200:404,headers:PRIVATE_HEADERS})}catch(e){return adminError(e)}}
export async function POST(request:Request,{params}:Context){const denied=await guard(request);if(denied)return denied;const uploaded:string[]=[];let committed=false;try{const id=(await params).id,old=await getOrder(id);if(!old)return Response.json({error:'ההזמנה לא נמצאה.'},{status:404});const form=await readLimitedForm(request);let value:Record<string,unknown>;try{value=JSON.parse(String(form.get('order')||''))}catch{return Response.json({error:'פרטי הזמנה לא תקינים.'},{status:400})}if(value.version!==old.version)throw Error('conflict');let o;try{o=editOrder(old,value,await getPricing())}catch(e){return Response.json({error:e instanceof Error?e.message:'פרטים לא תקינים'},{status:400,headers:PRIVATE_HEADERS})}
 const keep=value.keep;if(!Array.isArray(keep)||keep.some(k=>typeof k!=='string'||!old.images.some(i=>i.key===k))||new Set(keep).size!==keep.length)return Response.json({error:'רשימת תמונות לא תקינה.'},{status:400});
 const files=form.getAll('images').filter((f):f is File=>f instanceof File&&f.size>0);const error=imageUploadError(files);if(error)return Response.json({error},{status:400});if(keep.length+files.length>20)return Response.json({error:'אפשר לשמור עד 20 תמונות בהזמנה, כולל עיצובים.'},{status:400});
 const {BUCKET}=bindings();const imageRoles=value.imageRoles as Record<string,string>|undefined;o.images=old.images.filter(i=>keep.includes(i.key)).map(i=>({...i,role:imageRoles&&["reference","design","print"].includes(imageRoles[i.key])?imageRoles[i.key]:i.role}));let bytes=0;for(const i of o.images){bytes+=i.size??(await BUCKET.head(i.key))?.size??0}bytes+=files.reduce((n,f)=>n+f.size,0);if(bytes>30*1024*1024)return Response.json({error:'אפשר לשמור עד 30MB תמונות להזמנה.'},{status:400});
 const roles=form.getAll('roles').map(String);for(let i=0;i<files.length;i++){const f=files[i],buffer=await f.arrayBuffer();if(!validImage(new Uint8Array(buffer),f.type))return Response.json({error:'אחד הקבצים אינו תמונה תקינה.'},{status:400});const key=`orders/${id}/reference-${crypto.randomUUID()}`;await BUCKET.put(key,buffer,{httpMetadata:{contentType:f.type}});uploaded.push(key);o.images.push({name:f.name.slice(0,200),key,size:f.size,role:['reference','design','print'].includes(roles[i])?roles[i]:'reference'})}
 const changes=[];if(old.status!==o.status)changes.push('שלב: '+stageLabel(old.status)+' ← '+stageLabel(o.status));if(['name','phone','email','address'].some(k=>old[k as keyof typeof old]!==o[k as keyof typeof o]))changes.push('פרטי לקוח');if(JSON.stringify(old.shirts)!==JSON.stringify(o.shirts)||old.quantity!==o.quantity||old.package!==o.package)changes.push('חבילה וחולצות');if(old.price!==o.price)changes.push('מחיר');if(old.brief!==o.brief)changes.push('בריף');if(files.length||keep.length!==old.images.length)changes.push('תמונות');
 const saved=await saveOrder(o,old.version!,`עודכנו ${changes.join(', ')||'פרטי טיפול'}`,'מנהל');committed=true;await Promise.allSettled(old.images.filter(i=>!keep.includes(i.key)).map(i=>BUCKET.delete(i.key)));return Response.json(saved,{headers:PRIVATE_HEADERS});
 }catch(e){return adminError(e)}finally{if(!committed&&uploaded.length)await Promise.allSettled(uploaded.map(k=>bindings().BUCKET.delete(k)))}}
