'use client';
import {useEffect,useState} from 'react';
import {COLOR_LABELS} from '@/lib/catalog';
import './review.css';
type Preview={approvalId:string;state:string;quantity:number;shirts:{size:string;color:string}[];images:{name:string}[];comment?:string};
export default function Review({id}:{id:string}){
 const [data,setData]=useState<Preview|null>(null),[token,setToken]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[comment,setComment]=useState(''),[confirmed,setConfirmed]=useState(false);
 useEffect(()=>{const t=location.hash.slice(1);setToken(t);fetch(`/api/design/${id}?token=${encodeURIComponent(t)}`).then(async r=>{const v=await r.json() as Preview&{error?:string};if(!r.ok)throw Error(v.error);setData(v)}).catch(e=>setError(e.message))},[id]);
 async function respond(state:string){if(!name.trim()||state==='changes'&&!comment.trim()||state==='approved'&&!confirmed){setError('מלאו שם ואישור בדיקה, או פירוט לבקשת התיקון.');return}setBusy(true);setError('');try{const r=await fetch(`/api/design/${id}?token=${encodeURIComponent(token)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approvalId:data?.approvalId,state,name,comment})});const v=await r.json() as {error?:string};if(!r.ok)throw Error(v.error);setData(d=>d?{...d,state,comment}:d)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="design-review" dir="rtl"><header><b dir="ltr">PARTYPRINT ✳</b><span>מהרעיון שלכם. לחולצה שלכם.</span></header><section><p className="review-eyebrow">הרגע שלפני ההדפסה</p><h1>העיצוב שלכם מוכן.<br/>עכשיו תורכם להגיד וואו.</h1>{error&&<p role="alert" className="review-error">{error}</p>}{!data&&!error&&<p>טוענים את העיצוב הפרטי שלכם…</p>}{data&&<><p>בדקו את התמונות, הכיתוב, המידות והצבעים. רק לאחר אישור נמשיך להדפסה.</p><div className="review-gallery">{data.images.map((i,n)=><a key={n} href={`/api/design/${id}?token=${encodeURIComponent(token)}&image=${n}`} target="_blank" rel="noreferrer"><img alt={'עיצוב לאישור: '+i.name} src={`/api/design/${id}?token=${encodeURIComponent(token)}&image=${n}`}/><span>פתיחה בגודל מלא ↗</span></a>)}</div><h2>{data.quantity} חולצות בעיצוב שלכם</h2><div className="review-shirts">{data.shirts.map((s,n)=><span key={n}>חולצה {n+1}: {s.size} · {COLOR_LABELS[s.color as keyof typeof COLOR_LABELS]}</span>)}</div>{data.state!=='pending'?<div className="review-success" role="status"><h2>{data.state==='approved'?'האישור נשמר. מתקדמים לחולצות!':'בקשת התיקון נשמרה. חוזרים לעיצוב.'}</h2>{data.comment&&<p>{data.comment}</p>}<p>הסטודיו רואה את התשובה שלכם במערכת.</p></div>:<fieldset disabled={busy}><label>השם שלכם<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} autoComplete="name"/></label><label>הערות או מה תרצו לשנות<textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={2000} rows={4}/></label><label className="review-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>בדקתי את העיצוב, הכיתוב, הכמות, המידות והצבעים ואני מאשר/ת את הגרסה המוצגת.</label><div className="review-buttons"><button onClick={()=>void respond('approved')} disabled={busy||!confirmed}>{busy?'שומרים…':'מאשרים את העיצוב ✳'}</button><button onClick={()=>void respond('changes')}>מבקשים תיקון</button></div><small>סבב תיקונים אחד כלול. כל סבב נוסף בתוספת 100 ₪, בתיאום עם הסטודיו. אין חיוב דרך העמוד.</small></fieldset>}</>}</section></main>
}
