import {getChatGPTUser} from '@/app/chatgpt-auth';
import {PRIVATE_HEADERS} from '@/lib/security';
import {bindings} from '@/lib/order-store';
import {normalizeOrder,Order} from '@/lib/orders';
import {getOwnerEmail,getTeam} from '@/lib/team';
import {TICKET_PRIORITIES,TICKET_STATUSES,Ticket,TicketAssignee,TicketPriority,TicketStatus} from '@/lib/ticketing';

export type TicketRow=Record<string,unknown>;
export function ticketFromRow(row:TicketRow):Ticket{return {id:String(row.id||''),title:String(row.title||''),description:String(row.description||''),status:(String(row.status||'open') as TicketStatus),priority:(String(row.priority||'normal') as TicketPriority),customerName:String(row.customer_name||''),customerEmail:String(row.customer_email||''),orderId:String(row.order_id||''),assigneeEmail:String(row.assignee_email||''),assigneeName:String(row.assignee_name||''),createdByEmail:String(row.created_by_email||''),createdByName:String(row.created_by_name||''),dueAt:String(row.due_at||''),createdAt:String(row.created_at||''),updatedAt:String(row.updated_at||''),version:Number(row.version||1),...(row.last_message!==undefined?{lastMessage:String(row.last_message||'')}: {})}}
export function failure(error:unknown){const message=error instanceof Error?error.message:'';const labels:Record<string,string>={conflict:'הטיקט עודכן במכשיר אחר. רעננו ונסו שוב.',order_not_found:'מספר ההזמנה לא נמצא במערכת.',assignee_not_found:'העובד שנבחר אינו מחובר לצוות.',invalid_input:'יש לבדוק את פרטי הטיקט.',ticket_not_found:'הטיקט לא נמצא.',empty_message:'כתבו הודעה לפני השליחה.'};const status=message==='conflict'?409:message==='ticket_not_found'?404:400;return Response.json({error:labels[message]||'לא ניתן להשלים את הפעולה. נסו שוב.'},{status,headers:PRIVATE_HEADERS})}
export function text(value:unknown,max:number,required=false){if(value===undefined||value===null){if(required)throw Error('invalid_input');return ''}if(typeof value!=='string'||value.length>max)throw Error('invalid_input');const result=value.trim();if(required&&!result)throw Error('invalid_input');return result}
export function enumValue<T extends readonly string[]>(value:unknown,values:T,fallback:T[number]):T[number]{return typeof value==='string'&&(values as readonly string[]).includes(value)?value as T[number]:fallback}
export function validEmail(value:string){return !value||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
export function validDate(value:string){return !value||/^\d{4}-\d{2}-\d{2}$/.test(value)}
export async function actor(){const user=await getChatGPTUser();return {email:(user?.email||getOwnerEmail()).toLowerCase(),name:user?.fullName||user?.email||'צוות PARTYPRINT'}}
export async function assignees():Promise<TicketAssignee[]>{const owner=getOwnerEmail();const team=await getTeam();const list=[{email:owner,name:'בעל האתר',role:'owner'},...team.members.map(member=>({email:member.email.toLowerCase(),name:member.name||member.email,role:member.role||'manager'}))];return list.filter((member,index)=>list.findIndex(item=>item.email===member.email)===index)}
export async function orderFor(id:string){if(!id)return null;const row=await bindings().DB.prepare('SELECT data FROM orders WHERE id=?').bind(id).first<{data:string}>();if(!row)throw Error('order_not_found');return normalizeOrder(JSON.parse(row.data) as Order)}
export function ensureTicketValues(payload:Record<string,unknown>){const title=text(payload.title,160,true),description=text(payload.description,10000),customerName=text(payload.customerName,120),customerEmail=text(payload.customerEmail,160),dueAt=text(payload.dueAt,10),orderId=text(payload.orderId,120),status=enumValue(payload.status,TICKET_STATUSES,'open'),priority=enumValue(payload.priority,TICKET_PRIORITIES,'normal');if(!validEmail(customerEmail)||!validDate(dueAt))throw Error('invalid_input');return {title,description,customerName,customerEmail,dueAt,orderId,status,priority}}
export async function resolveAssignee(value:unknown){const email=text(value||'',160).toLowerCase();if(!email)return {email:'',name:''};const match=(await assignees()).find(member=>member.email===email);if(!match)throw Error('assignee_not_found');return {email:match.email,name:match.name}}
export function newId(){return crypto.randomUUID()}
