/* eslint-disable @next/next/no-img-element -- editorial images can be selected from the admin and may be local or external URLs. */
import Link from '@/components/safe-link';
import type {Metadata} from 'next';
import {getBlogPost,listBlogPosts} from '@/lib/blog';
import type {BlogPost} from '@/lib/blog';
import SeoFooterLinks from '@/components/seo-footer-links';
import '../blog.css';

export const dynamic='force-dynamic';

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const post=await getBlogPost(decodeURIComponent(slug));if(!post)return {title:'הפוסט לא נמצא | PARTYPRINT'};return {title:post.seoTitle||post.title,description:post.seoDescription||post.excerpt,keywords:post.keywords,alternates:{canonical:'/blog/'+post.slug},openGraph:{title:post.seoTitle||post.title,description:post.seoDescription||post.excerpt,type:'article',images:post.coverImage?[{url:post.coverImage,alt:post.coverAlt}]:[]}}}

export default async function BlogPostPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;
 const post=await getBlogPost(decodeURIComponent(slug));
 if(!post)return <main className="blog-page" dir="rtl"><BlogNav/><section className="blog-post-shell blog-not-found"><h1>הפוסט לא נמצא</h1><p>יכול להיות שהקישור השתנה.</p><Link className="blog-back-link" href="/blog">חזרה לכל הפוסטים ←</Link></section><BlogFooter/></main>;
 const allPosts=await listBlogPosts();
 const related=allPosts.filter(item=>item.id!==post.id).slice(0,3);
 const blocks=post.content.split(/\n\s*\n/).filter(Boolean);
 const readingTime=Math.max(3,Math.ceil(post.content.split(/\s+/).length/180));
 const faqSchema=post.faqs.map(item=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}));
 const articleSchema={'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.excerpt,image:[post.coverImage,post.inlineImage1,post.inlineImage2].filter(Boolean),author:{'@type':'Organization',name:post.author},datePublished:post.publishedAt||post.createdAt,dateModified:post.updatedAt,mainEntityOfPage:{'@type':'WebPage','@id':'https://partyprint.co.il/blog/'+post.slug}};
 const faqPageSchema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqSchema};
 return <main className="blog-post-page" dir="rtl"><BlogNav/><article className="blog-post-shell"><nav className="blog-breadcrumbs" aria-label="פירורי לחם"><Link href="/">PartyPrint</Link><span aria-hidden="true">←</span><Link href="/blog">בלוג</Link><span aria-hidden="true">←</span><span aria-current="page">{post.title}</span></nav><header className="blog-post-header"><span className="blog-category">מדריך PARTYPRINT</span><h1>{post.title}</h1><p>{post.excerpt}</p><div className="blog-post-meta"><span>מאת {post.author}</span><span>{readingTime} דקות קריאה</span><span>10 תשובות שימושיות</span></div></header><figure className="blog-cover"><img src={post.coverImage} alt={post.coverAlt} loading="eager"/></figure><div id="post-content" className="blog-post-content">{blocks.map((block,index)=><ContentBlock key={index} block={block}/>)}</div><InlineImage src={post.inlineImage1} alt={post.inlineImage1Alt}/><div className="blog-cta"><div><strong>יש לכם רעיון שכדאי להפוך לחולצה?</strong><span>שלחו רעיון ותמונות. מתחילים בלי חיוב.</span></div><Link href="/#order">מתחילים בלי חיוב <span aria-hidden="true">←</span></Link></div><InlineImage src={post.inlineImage2} alt={post.inlineImage2Alt}/><section className="blog-faq" aria-labelledby="post-faq"><h2 id="post-faq">10 שאלות ששואלים אותנו</h2><p className="blog-section-intro">תשובות קצרות שיעזרו לכם להבין אם זה מתאים לאירוע שלכם.</p>{post.faqs.map((item,index)=><details key={index}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section><section className="blog-related" aria-labelledby="related-links"><h2 id="related-links">קישורים שכדאי לפתוח</h2><div className="blog-related-links">{post.internalLinks.map((item,index)=><Link key={index} href={item.href}>{item.label} <span aria-hidden="true">↗</span></Link>)}</div></section>{related.length>0&&<RelatedPosts posts={related}/>}</article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema).replace(/</g,'\\u003c')}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqPageSchema).replace(/</g,'\\u003c')}}/><div className="blog-mobile-cta"><div><strong>מוכנים לעצב?</strong><span>מתחילים בלי חיוב</span></div><Link href="/#order">שליחת רעיון <span aria-hidden="true">←</span></Link></div><BlogFooter/></main>
}

function ContentBlock({block}:{block:string}){const lines=block.split('\n');if(lines[0].startsWith('# '))return null;if(lines[0].startsWith('## '))return <h2>{lines[0].slice(3)}</h2>;if(lines.every(line=>line.startsWith('- ')))return <ul>{lines.map((line,index)=><li key={index}>{line.slice(2)}</li>)}</ul>;return <p>{lines.map((line,index)=><span key={index}>{index>0&&<br/>}{line}</span>)}</p>}
function InlineImage({src,alt}:{src:string;alt:string}){return src?<figure className="blog-inline-image"><img src={src} alt={alt||'תמונה מתוך מדריך PARTYPRINT'} loading="lazy"/><figcaption>{alt||'השראה לעיצוב אישי'}</figcaption></figure>:null}
function RelatedPosts({posts}:{posts:BlogPost[]}){return <section className="blog-related-posts" aria-labelledby="related-posts"><div className="blog-related-posts-head"><div><span className="blog-kicker">KEEP EXPLORING</span><h2 id="related-posts">עוד רעיונות שיכולים להתאים</h2></div><Link href="/blog">לכל המדריכים ←</Link></div><div className="blog-related-post-grid">{posts.map(post=><Link className="blog-related-post" href={'/blog/'+post.slug} key={post.id}><img src={post.coverImage} alt={post.coverAlt} loading="lazy"/><div><span>{post.keywords[0]||'PARTYPRINT'}</span><strong>{post.title}</strong></div></Link>)}</div></section>}
function BlogNav(){return <header className="blog-nav"><Link className="blog-brand" href="/" aria-label="PARTYPRINT — חזרה לאתר"/><nav className="blog-nav-links"><Link href="/">האתר הראשי</Link><Link href="/#packages">החבילות</Link><Link href="/#faq">שאלות נפוצות</Link></nav><Link className="blog-nav-cta" href="/#order">מתחילים בלי חיוב</Link></header>}
function BlogFooter(){return <footer className="blog-footer"><SeoFooterLinks/><div className="blog-footer-bottom"><strong>PARTYPRINT · אנשים אמיתיים. עיצובים לא רגילים.</strong><Link href="/">חזרה לאתר הראשי</Link></div></footer>}
